### ISSUE TITLE
Does `maxZoom` specify when markercluster should stop?

### ISSUE THREAD

**Issue by tristen** [mapbox/supercluster#1]
@mourner I'm working off your [supercluster branch](https://github.com/mapbox/mapbox-gl-js/tree/supercluster) in mapbox-gl-js and `maxZoom` has a [fixed value of 18](https://github.com/mapbox/mapbox-gl-js/blob/4358643223b13ab7d0d3520ea17e311815f9f08a/js/source/worker.js#L114). Does this mean markerclustering should not cluster >= zoom level 18? If that's the case it _appears_ to not be working:

![screen shot 2016-01-13 at 6 10 48 pm](https://cloud.githubusercontent.com/assets/61150/12310957/ad768944-ba21-11e5-8c79-9f812ba4e808.png)

Ideally, what I'm looking to do is expand points when a zoom level is reached (or when clustering doesn't make sense). I would expect the cluster containing "4" to expand out at some point in this example:

![threshold](https://cloud.githubusercontent.com/assets/61150/12310984/e73eb174-ba21-11e5-8853-e3605282b00f.gif)

**Comment by mourner** [comment]
It should expand in that branch on the last zoom level (as you can see in the gif I posted), but for that to work, GeoJSONSource maxzoom needs to be 1 level higher than the zoom you pass to supercluster. I'll make it automatic (see todo in https://github.com/mapbox/mapbox-gl-js/pull/1931)
