### ISSUE TITLE
getClusterExpansionZoom never returns zooms higher than maxZoom

### ISSUE THREAD

**Issue by cherniavskii** [mapbox/supercluster#105]
## Steps to reproduce:

1. Run supercluster demo.
2. Set `maxZoom` to 4.
3. Click on cluster on zoom 4.

## Expected result:

Map should zoom in and cluster should expand.

## Actual result:

Map centered on cluster, but cluster doesn't expand.

![supercluster](https://user-images.githubusercontent.com/13808724/48001319-8577a980-e108-11e8-88c9-331b05d4c7bb.gif)

## Additional info
The issue is in `getClusterExpansionZoom` - it never return zoom higher than `maxZoom`:

```js
getClusterExpansionZoom(clusterId) {
        let clusterZoom = (clusterId % 32) - 1;
        while (clusterZoom < this.options.maxZoom) {
            const children = this.getChildren(clusterId);
            clusterZoom++;
            if (children.length !== 1) break;
            clusterId = children[0].properties.cluster_id;
        }
        return clusterZoom;
    }
```

I can submit a PR :)

**Comment by mourner** [comment]
@cherniavskii good catch! Looks like the fix here would be to change `<` to `<=` in `(clusterZoom < this.options.maxZoom)` condition. Want to PR and check that it works?

**Comment by mourner** [comment]
This PR seems related too: #76

**Comment by cherniavskii** [comment]
Yeah, looks like it address the same issue
