### ISSUE TITLE
Custom groups

### ISSUE THREAD

**Issue by snuuve** [mapbox/supercluster#117]
Is it possible to make custom groups ?
I.E.
I have 3 types of markers on map: A, B, C and i want to make cluster groups. 
Clusters for A markers.
Clusters for B markers.
Clusters for C markers.

**Comment by mourner** [comment]
No, you'll have to create separate Supercluster indexes for each group.

**Comment by MaevskiyE** [comment]
HI @mourner , I believe that I'm doing something wrong. I looked in documentation and everywhere I could. But only this topic looks similar to my goal. I have different kind of markers that I want to clusterize not all together, but by type. So only definite type should be inside cluster

I created two separate indexes and putting them one by one. But unfortunately I see only last one on map. Maybe you can suggest something?

`  index = new Supercluster().load(features);
  index2 = new Supercluster().load(features2);

self.onmessage = function (e) {
  if (e.data.markers) {
    loadPoints(e.data.markers);
  } else if (e.data.getClusterExpansionZoom) {
    postMessage({
      expansionZoom: index.getClusterExpansionZoom(e.data.getClusterExpansionZoom),
      center: e.data.center,
    });
  } else if (e.data.bbox && e.data.zoom) {
    postMessage(index.getClusters(e.data.bbox, e.data.zoom));
    postMessage(index2.getClusters(e.data.bbox, e.data.zoom));
  }
};`

Thank you in advance
