### ISSUE TITLE
Limit cluster within country boundaries

### ISSUE THREAD

**Issue by daltonos** [mapbox/supercluster#123]
Is there a way for limiting a cluster to a country? 
Sometimes the radius might cover more than a country, and then markers from different countries could get clustered together. Is there a way to avoid that?

If not implemented yet? any hints on how to start?
maybe some area of the code where we could overwrite the comparison/distance function so that it checks first if two markers are in the same country/state etc?

Thanks a lot.
Awesome library.

**Comment by mourner** [comment]
No, unfortunately there's no way to do this with Supercluster, and no plans to implement this because it would require a completely different, complicated approach to processing points.

**Comment by daltonos** [comment]
alright. thanks for the reply.
