### ISSUE TITLE
why bounding box values are updating?

### ISSUE THREAD

**Issue by jpnathannew** [mapbox/supercluster#125]
Team, 
Hope you are doing great. 

in **getClusters** function why you are updating the bounding box values

```
let minLng = ((bbox[0] + 180) % 360 + 360) % 360 - 180;
const minLat = Math.max(-90, Math.min(90, bbox[1]));
let maxLng = bbox[2] === 180 ? 180 : ((bbox[2] + 180) % 360 + 360) % 360 - 180;
const maxLat = Math.max(-90, Math.min(90, bbox[3]));
```
For me it is not returning exact response

When I update the above code like this
```
        var minLng = bbox[0]; //((bbox[0] + 180) % 360 + 360) % 360 - 180;
        var minLat = bbox[1]; //Math.max(-90, Math.min(90, bbox[1]));
        var maxLng = bbox[2]; //((bbox[2] + 180) % 360 + 360) % 360 - 180;
        var maxLat = bbox[3]; //Math.max(-90, Math.min(90, bbox[3]));
```

It is working. Can you please explain what is the reason you guys added this.

Eg Code: 

```
var bbox = [ '-198.28125',
  '-48.57478991092885',
  '82.96875000000001',
  '63.54855223203644' ];

let minLng = ((bbox[0] + 180) % 360 + 360) % 360 - 180;
const minLat = Math.max(-90, Math.min(90, bbox[1]));
let maxLng = bbox[2] === 180 ? 180 : ((bbox[2] + 180) % 360 + 360) % 360 - 180;
const maxLat = Math.max(-90, Math.min(90, bbox[3]));

console.log(minLng);
console.log(minLat);
console.log(maxLng);
console.log(maxLat);

```

Above code is returning 
-18.281251800000007
-48.57478991092885
-97.03125
63.54855223203644

**Comment by jpnathannew** [comment]
I passed Australia map bounding box. But I am not getting any clustering. When I check the code points are changed to south america bounding box

Passed Bounding box values:
(99.09667968750001, -40.58058466412763, 169.40917968750003,-9.752370139173285)
http://bboxfinder.com/#-40.580585,99.096680,-9.752370,169.409180

But generated bounding box value:
(-80.9033203125,-40.58058466412763,-10.5908203125,-9.752370139173285)

http://bboxfinder.com/#-40.580585,-80.903320,-9.752370,-10.590820

**Comment by mourner** [comment]
You pass bbox values as strings. You forgot to convert them to numbers.

**Comment by jpnathannew** [comment]
@mourner  thanks for your quick resolution. It is working perfectly
