### ISSUE TITLE
IE 11 - Crash after upgrading from v4.1.1

### ISSUE THREAD

**Issue by MarcusPenn** [mapbox/supercluster#127]
Hi All,

This may be related to #113.

I recently tried upgrading supercluster from v4.1.1 to v6.0.1 and failing that v5.0.0. However this causes my entire site to not load on IE 11.

The only error I get in the console is a [SCRIPT1002](https://docs.microsoft.com/en-us/scripting/javascript/misc/syntax-error-javascript): Syntax error

I have made the changes required for the upgrade to v5.0.0:
`clusterer = new Supercluster({ radius: 25 });` 

I only made use of 3 of the available methods:
`this.clusterer.getClusterExpansionZoom(...)`
`this.clusterer.load(...)`
` this.clusterer.getClusters(...)`

Many thanks,

**Comment by mourner** [comment]
The browser builds of Supercluster (https://unpkg.com/supercluster@6.0.1/dist/supercluster.min.js) are transpiled and don't have this problem. The same build is put under `main` entry point of Supercluster `package.json`. If you see errors in IE related to Supercluster, there's something wrong with your app configuration / bundling that makes it use the wrong bundle (module one, which is ES6).

**Comment by NeliHarbuzava** [comment]
I used to transpile `supercluster` and its dependency `kdbush` to make it work in IE;
```js
const modulesToTranspile = ['supercluster', 'kdbush'];

// webpack config for babel-loader
include: modulesToTranspile.map(moduleName =>
    path.resolve(__dirname, `../../../../node_modules/${moduleName}`)
),
exclude: [new RegExp(`node_modules\/(?!(${modulesToTranspile.join('|')}))`)]
```
