### ISSUE TITLE
Clusters zoom in / out - higher numbers on cluster if zoom in

### ISSUE THREAD

**Issue by ikuzniar** [mapbox/supercluster#129]
The effect which we would like to have is:
unzoomed - higher number on cluster 
zoom in - smaller number on cluster

Please see the examples on screen what we have today. Could you please let us know why we could get on one case multiple clusters and seperate icons and on the other the clusters only. What trigger it?

![Screenshot_20190716-123621_Kontiki](https://user-images.githubusercontent.com/52959482/61290153-77b41100-a7cb-11e9-9c16-a1e6eaf4a12b.jpg)
![Screenshot_20190716-123639_Kontiki](https://user-images.githubusercontent.com/52959482/61290155-77b41100-a7cb-11e9-9126-d0f12ed1093b.jpg)
![Screenshot_20190716-123648_Kontiki](https://user-images.githubusercontent.com/52959482/61290156-77b41100-a7cb-11e9-894b-d6533f47c81d.jpg)
![Screenshot_20190716-123921_Kontiki](https://user-images.githubusercontent.com/52959482/61290157-784ca780-a7cb-11e9-9d38-9e2e12787eb6.jpg)
![Screenshot_20190716-123936_Kontiki](https://user-images.githubusercontent.com/52959482/61290158-784ca780-a7cb-11e9-81de-7490349fe524.jpg)
![Screenshot_20190716-123940_Kontiki](https://user-images.githubusercontent.com/52959482/61290159-784ca780-a7cb-11e9-8a2a-b5a96896b8e4.jpg)
![Screenshot_20190716-123953_Kontiki](https://user-images.githubusercontent.com/52959482/61290161-784ca780-a7cb-11e9-8fc5-8d143271672f.jpg)

**Comment by mourner** [comment]
It's very hard to understand what issue you're having just looking at the screenshots. Can you provide a minimal **live** test case that demonstrates it, and provide a more detailed description what you expect to see and what you see instead? (Filling our the provided issue template)
