### ISSUE TITLE
Store point ids as cluster property

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/supercluster#13]
Hi there! There is no way to get points inside the cluster, maybe we can store point ids as cluster property?

**Comment by antoniogiordano** [comment]
Hi step,

istarkov forked the project adding the points array to the cluster object, and i refork his project adding an id field to every points passed to the cluster generation, don't know if it's useful for you, maybe yes ^^ https://github.com/antoniogiordano/supercluster

**Comment by stepankuzmin** [comment]
I think that it would be useful to have this functionality in supercluster core.
