### ISSUE TITLE
Questions about map and reduce options

### ISSUE THREAD

**Issue by bclinkinbeard** [mapbox/supercluster#130]
I'm having a really hard time understanding the behavior of map and reduce. If I pass 50 features into `load`, my `map` function gets called hundreds of times. Is that just because each point is processed multiple times? I also don't understand how I end up logging out empty objects with the code below. Shouldn't there always be a `foo` property on `props`?

```
map: p => ({foo: 'bar'}),
reduce: (acc, props) => {
    console.log(props);
},
```

I'm also unclear how initialization is supposed to work now that the `initial` option is gone. If each of my features has a `timestamp` property and I want to collect them on each cluster for doing calcs, do I need to conditionally instantiate a collector prop on `acc`? `if (!acc.times) acc.times = [];`?

I've tried a lot of combos of things and nothing seems to work predictably. What am I doing wrong? Am I better off doing everything with calls to `getLeaves` after the fact?

**Comment by mourner** [comment]
> If I pass 50 features into load, my map function gets called hundreds of times. Is that just because each point is processed multiple times?

Looks like it currently gets called for every unclustered point on every zoom level, which is wasteful — we can avoid that if there are no neighbors to cluster with. Good catch, I'll put up a PR.

>  I also don't understand how I end up logging out empty objects with the code below. Shouldn't there always be a foo property on props?

That I can't say without a concrete test case. It works properly on the test fixture, which I just checked by adding a `console.log` in the corresponding test.

> I'm also unclear how initialization is supposed to work now that the initial option is gone. If each of my features has a timestamp property and I want to collect them on each cluster for doing calcs, do I need to conditionally instantiate a collector prop on acc? if (!acc.times) acc.times = [];?

As described [in the changelog](https://github.com/mapbox/supercluster/releases/tag/v6.0.0), now each cluster is implicitly initialized with the point it grows out of. This means that you would define anything you need in the cluster in `map` — e.g. `(props) => ({times: [props.timestamp]})`. However, I would strongly recommend against accumulating values in arrays as a part of `reduce` — reduce is meant for _reduction_, and accumulating arrays just asks for serious performance / memory problems.
