### ISSUE TITLE
getting Cannot read property 'range' of undefined, when max zoom level limit exceed

### ISSUE THREAD

**Issue by jpnathannew** [mapbox/supercluster#133]
my max zoom level is 16

When i pass below coordinates 
 -77.23710000514986 (_southWest lat)
38.93216896850752 (_northEast lat)
-77.2286081314087 (_southWest lng)
38.933979996819886(_northEast lng)
and  Zoom level is : 17

I am getting error like 
 **TypeError: Cannot read property 'range' of undefined  at Supercluster.getClusters** 

After max zoom level(16) it should return the markers inside bounding box. But it is throwing error

Please give me some suggestion

**Comment by mourner** [comment]
Please provide a fully self-contained test case — this is not enough to diagnose the issue.

**Comment by jpnathannew** [comment]
Ya Sure. 
Leaflet map max zoom level is 18. If I set mazZoom value as 16
```
 layer.clusterIndex = new Supercluster({
        log: true,
        radius: layer.clusterRadius,
        extent: layer.clusterExtent,
        maxZoom: 16,
    }).load(geojson);
```
So every time it is clustering upto 16th zoom level and working fine. If I pass zoom value as 17 from UI, I am getting error saying
`TypeError: Cannot read property 'range' of undefined at Supercluster.getClusters`
Because maxZoom value is 16 but I am passing 17 zoom level with bounding box values from UI

**Comment by mourner** [comment]
That's not a self-contained test case. Can you set something minimal up on e.g. https://jsfiddle.net/?

**Comment by jpnathannew** [comment]
@mourner Found the reason latest change (6.0.2) only this issue. will give you the fiddle

**Comment by mourner** [comment]
Closing since no test case was provided.
