### ISSUE TITLE
How to work with fractional zoom levels

### ISSUE THREAD

**Issue by WYSwolf** [mapbox/supercluster#137]
I am trying to use supercluster with fractional zoom levels.
I can see that the supercluster can only be added/updated on integer zoom levels, which is also mentioned in the document.
But if it is possible that the supercluster can also work with fractional zoom levels?

**Comment by mourner** [comment]
Unfortunately not. The core algorithm of this library works with integer levels. Making a hierarchical clustering solution for fractional zoom levels would likely require a completely different algorithm.
