### ISSUE TITLE
Indeterministic behaviour over runs at same zoom level

### ISSUE THREAD

**Issue by theochampion** [mapbox/supercluster#139]
Hi there!

I'm using supercluster to cluster points in realtime on my client (generating cluster only at the zoom level I currently am) but I noticed something weird.
When the viewport change, I re fetch my points and re run the clustering on them, the resulting clusters are arranged differently (as shown below) than before even tho the points and zoom level is the same.

![ss](https://user-images.githubusercontent.com/14275989/65712418-498a6180-e097-11e9-935b-7c9b8009c68f.gif)

Is this normal behavior?

Cheers!

**Comment by mourner** [comment]
Yes. Supercluster implements a greedy clustering algorithm, meaning that order of input matters. When you change the viewport, the order of points changes as well, leading to slightly different clusters. For a stable experience, you'd have to cluster the whole dataset at once on the server, and then pull already clustered data.

**Comment by theochampion** [comment]
@mourner Thanks for the clarification, appreciate it :)

Dataset is highly dynamic (real-time) so doing the clustering server-side is not possible in my case.
If the clusters depend only on the order of the input, ordering them (by id for example) before the clustering could solve the problem or am I missing something?

**Comment by theochampion** [comment]
Appeared to be a problem in my Dart implementation of the algorithm, now works with the list ordered by ID :)

**Comment by mourner** [comment]
Glad it helped!
