### ISSUE TITLE
How i can accumulate unique values is cluster?

### ISSUE THREAD

**Issue by Akiyamka** [mapbox/supercluster#142]
Hello!
I need to collect a set of icons from the features that got into the cluster.
I write map reduce pair:
```js
const joinSets = (setA, setB) => (setB.forEach(i => setA.add(i)), setA);

/* *** */

map: props => ({ icons: new Set([props.icon]) }),
reduce: (accumulated, props) => {
  accumulated.icons = joinSets(accumulated.icons, props.icons);
}

```
But with this code sometimes i see cluster with **two** features (i check this by getLeves method) but **three** different icons in cluster property.

Am I doing something wrong?

**Comment by Akiyamka** [comment]
The reason for the effect described above is that in `joinSets` function in that I changed the first set instead of a full copy. So in reduce js only copy a reference to set, because of what it became same for different branches. 
I solved this problem by encoding a set of icons in a bit mask, since making a full copy of each iteration is too expensive.

**Comment by mourner** [comment]
Yeah, you have to be careful to keep the properties that get accumulated immutable. Nice solution!
