### ISSUE TITLE
toGeoJSON() supercluster layer

### ISSUE THREAD

**Issue by VladimirKalachikhin** [mapbox/supercluster#147]
If I  do `toGeoJSON()` for superclaster layer, the result GeoJSON object has only one Point, not all.

**Comment by mourner** [comment]
`toGeoJSON` where? Can you provide a minimal reproducible test case? There's not enough information to diagnose the issue.

**Comment by VladimirKalachikhin** [comment]
Ok, it is not a bug.
Typical `update` function contains:
```
function update() {
        .....
	layerWithPoints.clearLayers();                                 // empty the layer
	layerWithPoints.addData(pointsList.getClusters(..., ...));     // add some points
}
```
so the `layerWithPoints` does not contain all points (from supercluster `pointsList`) at any given time. And `layerWithPoints.toGeoJSON()` creates a GeoJSON with the current visible points only - in typical case. This is correct, but not immediately obvious.
