### ISSUE TITLE
Pinch zoom in Leaflet lead to "TypeError: undefined is not an object (evaluating 'tree.range')"

### ISSUE THREAD

**Issue by jabidof** [mapbox/supercluster#148]
When pinch-zooming on leaflet I do a clusters recalculation like so:
`const clusterizedMarkers = index.getClusters(clustersBounds, zoom);
`
The zoom has sometimes non integer values coming from Leaflet:
`From my console: zoom value – 8.383082795293051`
At that moment, index.getClusters crashes the app as the zoom value is not an integer (which makes sense!)

The fix in that case is to change above code to:
`const clusterizedMarkers = index.getClusters(clustersBounds, parseInt(zoom));
`

**I'm happy with this fix and I thought it could help other but it would most probably be better to solve this directly in "supercluster" lib...**

Enjoy the weekend

**Comment by Ej-leone** [comment]
This error still persists

**Comment by PrayaAmadigaPitasa** [comment]
yep, after I debug the tree field. the value is an array of cluster.
so tree.range will cause error

**Comment by JClackett** [comment]
Still getting this error

var tree = this.trees[this._limitZoom(zoom)];

tree is undefined
