### ISSUE TITLE
it's really super fast. can we using this in the leaflet.clustermarker plugin ?

### ISSUE THREAD

**Issue by kocokolo** [mapbox/supercluster#15]
if can ,can you tell how to join this in  ?

thank you

**Comment by mourner** [comment]
There's a Leaflet demo here https://github.com/mapbox/supercluster/tree/master/demo. I believe it's very hard to integrate this into Leaflet.MarkerCluster — you get great performance at expense of not being able to animate clusters and add/remove points dynamically.

**Comment by kocokolo** [comment]
Thank you very much .

If you come to chinae ,i would like to have a coffee with you .

thank you for your great jod ,and the Leaflet really made great help for me.
