### ISSUE TITLE
Generate places.json/places-z0-0-0.json

### ISSUE THREAD

**Issue by spkostas** [mapbox/supercluster#154]
Can i re-generate places.json,places-z0-0-0.json in order to cluster new locations?

**Comment by mourner** [comment]
I'm not sure what this meant, but `places.json` is a test fixture meant for core contributors to the library.

**Comment by spkostas** [comment]
Sorry , i meant how do i cluster new locations? Is it possible to cluster around 8million markers?
Thanks in advance
