### ISSUE TITLE
Question on how to access all cluster leaves inluding the leaves of undelying clusters.

### ISSUE THREAD

**Issue by melhirech** [mapbox/supercluster#158]
Hello everyone,

I'm using supercluster with react google maps in order to group my markers in clusters (for performance purposes).
Now on each cluster I want to display the sum of a value in my marker/point.

Illustration:
![Untitled Diagram (2)](https://user-images.githubusercontent.com/26940716/86253347-b72e6580-bbb4-11ea-9953-65e5b0b1f303.jpg)

I used the getLeaves method but it only retruns leaves and not undelying clusters.

Anyone has an idea on how to achieve this with supercluster?

**Comment by mourner** [comment]
`getLeaves` should return all leaves of a cluster, including leaves of nested clusters. If it doesn't please share a minimal test case that reproduces the issue.

**Comment by melhirech** [comment]
This is a link to the code I'm using.
https://stackblitz.com/edit/react-rmlrjl?file=Map.js

**Comment by mourner** [comment]
@melhirech if this happens, it might be a bug, but I haven't seen this before. Also, the code you linked shows me some React error and doesn't run. Can you please try creating a _minimal_ test case (so, e.g. plain JS with Supercluster + some GeoJSON test data that could be run under Node, no React/UI/etc)?

**Comment by mourner** [comment]
Oh, I think I see the problem in the code — `getLeaves` without arguments returns a [max of 10 items](https://github.com/mapbox/supercluster#getleavesclusterid-limit--10-offset--0) by default. You would have to call `getLeaves(clusterId, Infinity)` to get all the results.

**Comment by melhirech** [comment]
@mourner Thanks a lot, that's exactly what was missing.
With `getLeaves(clusterId, Infinity)` I get all the leaves instead of 10 max. It's clear in the docs, but I missed it.
