### ISSUE TITLE
Question: Is there interest/bandwidth to port this to Potly Dash?

### ISSUE THREAD

**Issue by zeluspudding** [mapbox/supercluster#159]
Howdy Mapbox team!
First off, I just wanted to say you guys are awesome - Mapbox is such a delight to use :)

I've entered this issue tracker simply to ask if there are plans or interest in porting this package as a Dash-Component.

[Chris Parmer at Plotly mentioned how](https://community.plotly.com/t/how-to-use-mapbox-clusters/10774/7?u=agosta)
> all [dash] mapbox chart types have been sponsored by organizations

His comment came on the heals of my troubleshooting issues with the current `dash-leaflet` component which [struggles to cluster and visualize 20k+ points in less than 10 seconds](https://github.com/thedirtyfew/dash-leaflet/issues/24#issuecomment-657109594).

Would you sponsor this and if so what would that entail? Thanks in advance :)

**Comment by mourner** [comment]
Unfortunately no, but I'd be happy if someone does contribute.

**Comment by zeluspudding** [comment]
It is happening [over here](https://github.com/thedirtyfew/dash-leaflet/issues/24#issuecomment-657506577)
