### ISSUE TITLE
Possible to label/color markers and spiderfy on zoom?

### ISSUE THREAD

**Issue by zeluspudding** [mapbox/supercluster#160]
@emilhe is doing a superb job porting super cluster to plotly's `dash` [over here](https://github.com/thedirtyfew/dash-leaflet/issues/24#issuecomment-657506577) and I must say its performance mapping 30k points is amazing (so cool you've gotten it to map millions more!). 

One thing that's unclear is if there's an option to "spiderfy" points. I know the question was [asked in 2017](https://github.com/mapbox/supercluster/issues/34#issuecomment-273759596) but not sure if this functionality came to be. I am especially missing this functionality since I've cases in my dataset with 1000 points at one location... but in supercluster it is hard to appreciate this phenomena because all 1000 points are mapped on top of eachother, thus looking like only 1 point.

### with spiderfy using regular leaflet 1000 points look like 1000 points 
![image](https://user-images.githubusercontent.com/8431341/87425737-c85b7700-c5a3-11ea-9648-dfb67bcd03c8.png)

### without spiderfy using supercluster leaflet 1000 points looks like 1 point. 
![image](https://user-images.githubusercontent.com/8431341/87426703-3b192200-c5a5-11ea-9236-55fb7861d43c.png)

It's also unclear how to go about labeling and coloring individual markers. Is that possible? Thanks in advance :)

**Comment by mourner** [comment]
Spiderifying and styling options are out of scope for this library. All it does is hierarchical clustering; once you retrieve the objects for the current view, you can do anything with them. The Leaflet demo in the repo is just a demo.
