### ISSUE TITLE
How to avoid overlapping clusters

### ISSUE THREAD

**Issue by dcporter44** [mapbox/supercluster#161]
I am trying to reproduce the gif shown in the README where the cluster markers never overlap on the map.

However, my clusters are for some reason overlapping right on top of each other in high concentration areas. I would expect that instead of overlapping, they should simply join and add together. My config options look like this:

```
{
    radius: 100,
    maxZoom: 22,
    extent: 256,
    minPoints: 10
  }
```

What is the best way to avoid overlap? Is there some setting for merging clusters when they are within a certain range of each other?

**Comment by mourner** [comment]
I guess this might be because of the `minPoints: 10` option. For less overlapping, you would need to leave it at the default setting (`2`) so that points are always merged if they're close regardless of how many points there are, in addition to possibly increasing the radius.
