### ISSUE TITLE
Can't find supercluster.js under Demo

### ISSUE THREAD

**Issue by Shwetha9** [mapbox/supercluster#17]
Can't find supercluster.js under Demo

**Comment by karydja** [comment]
Hello, @Shwetha9 :smiley:  I was experiencing this same problem.

Please, read the note the author put in [demo/worker.js](https://github.com/mapbox/supercluster/blob/master/demo/worker.js#L3):

```
// generate supercluster.js from the repo root with:
// browserify index.js -s supercluster > demo/supercluster.js
```

**Comment by Shwetha9** [comment]
Awesome thanks!! Really helpful.

**Comment by ThomasG77** [comment]
There is a plan to publish the library on public cdn like cdnjs https://cdnjs.com or a MapBox public CDN like for Turf.js? I can submit a PR to https://github.com/cdnjs/cdnjs/

**Comment by mourner** [comment]
@ThomasG77 yes, although I prefer https://unpkg.com/.

**Comment by ThomasG77** [comment]
I've started a branch to publish to unpkg.org at https://github.com/webgeodatavore/supercluster/tree/publish-to-unpkg Is is good enough for a PR? It generates automatically the build and publish. The only issue is that it will applied only for next tagged version of supercluster. I also didn't automate with Travis the publication part on NPM

**Comment by mourner** [comment]
@ThomasG77 here's an example of how I do it in my projects: https://github.com/mapbox/earcut/blob/master/package.json#L9-L11

**Comment by ThomasG77** [comment]
I've done the changes, rebased and submit PR #22
