### ISSUE TITLE
Certain points not showing on a low zoom level

### ISSUE THREAD

**Issue by lsmienk** [mapbox/supercluster#171]
I am using Supercluster to load in points and then receive back the tiles, however certain point seem to disappear on higher zoom levels. 

I noticed that there where certain points that where not considered in the cluster count but when zooming in they did appear.
An example is that I had a cluster count of 5 (zoom level 0) but when zooming in I found 9 points. After playing around in my code I found that changing the radius from the standard 40 to a radius of 70 "solved" the problem for me. 

```
const cluster = new Supercluster({
      radius: 70,
      minZoom: 0,
      maxZoom: 12,
   });
```

**Comment by mourner** [comment]
Sorry for a late response! There's no way to know if this was an issue with Supercluster without a reproducible live test case, so I have to close the issue.
