### ISSUE TITLE
Using getLeaves randomly throws 'No cluster with the specified id'.

### ISSUE THREAD

**Issue by sarveshkolte** [mapbox/supercluster#172]
I'm using supercluster in a website where- whenever a user moves the map (mapbox-gl), the frontend sends a request to the backend with map bounds and current zoom level. 
I create a index using `const index = Supercluster({options}).load(points)`. What I want to achieve is whenever the frontend requests for features on the backend, the backend should find clusters inside the given bounds (I'm already able to achieve this) and then get 1 feature from the cluster and send it back to the fronted.

So here's the problem whenever I use `index.getLeaves(cluster_id, 1)` Supercluster randomly throws the Error `No Cluster with the specified Id` It works for some clusters but it doesn't for others. This behavior is not expected. It will be great if you can help.

Here is a test case-
```js
let index = new Supercluster({
	radius: 20,
	extent: 256,
	maxZoom: 23,
	minPoints: 2,
});
index.load(features); //load features

//This function runs whenever the frontend requests for features
getCluster(bounds, zoom){
    let clusters = clusterIndex.getClusters(bounds, zoom); //Array of clusters
    let features = [];
    clusters.forEach((cluster) => {
        if (!cluster) return;
        let feature = clusterIndex.getLeaves(cluster.id, 1); //randomly throws No cluster with the specified Id, 
        //I also tried 'cluster.properties.cluster_id' it still didn't work
        features.push(feature[0]);
    });
    return features;
}
```

**Comment by mourner** [comment]
Can you set up a full minimal reproducible test case for the issue? I wouldn't be able to diagnose just from the code cited since I don't know which set of features / bounds / zoom it fails on.

**Comment by sarveshkolte** [comment]
Alright

I want to keep my geojson data private so instead I randomly generated it.
The error is still there
```
const turf = require('@turf/turf');
const Supercluster = require('supercluster')
let features = turf.randomPoint(5000).features

let index = new Supercluster({
	radius: 40,
	extent: 256,
	maxZoom: 23,
	minPoints: 2,
});
index.load(features); //load features

//This function runs whenever the frontend requests for features
function getCluster(bounds, zoom){
    let clusters = index.getClusters(bounds, zoom); //Array of clusters
    let features = [];
    clusters.forEach((cluster) => {
        if (!cluster) return;
        let feature = index.getLeaves(cluster.id, 1); //randomly throws No cluster with the specified Id, 
        //I also tried 'cluster.properties.cluster_id' it still didn't work
        features.push(feature[0]);
    });
    return features;
}
var lines =  turf.randomLineString(25).features

var bbox = turf.bbox(lines[0]);
let result = getCluster([-180, -90, 180, 90], 2)

console.log(result) //if the code runs successfully there should be a feature in cluster variable

```

**Comment by mourner** [comment]
@sarveshkolte `getClusters` returns both clusters and individual unclustered points (that have no neighbors), have you tried checking `cluster.properties.cluster === true` before fetching leaves for it?

**Comment by sarveshkolte** [comment]
I just tried it and the error went away. Thank you very much. I'm sorry if you had to waste time on this.

**Comment by mourner** [comment]
No worries, glad it worked!
