### ISSUE TITLE
Fails to load 5 million geoJSON file 

### ISSUE THREAD

**Issue by 24thDawn** [mapbox/supercluster#175]
Following the guide [here ](https://stackoverflow.com/questions/51033188/how-to-use-supercluster) and editing this line
` getJSON('../test/fixtures/data.geojson ` in worker.js with smaller datasets (60k etc) works great.
However, pointing to a 5.7 million geoJSON dataset returns a blank map with no markers or clusters.
There is no error or crash the data simply fails to load.
How can I load a 5 million+ dataset and get it to work like in the demo video?

**Comment by mourner** [comment]
It should work in theory, although 5.7 million is quite a lot and might push browsers to their limit. However I can't diagnose any potential issue here without a live reproducible test case.

**Comment by 24thDawn** [comment]
Thanks for the tip, the dataset loads within seconds on Firefox but fails on Chrome.
Perhaps browser compatibility issues...regardless the map is now up and running.
