### ISSUE TITLE
The result of this getClusters is wrong

### ISSUE THREAD

**Issue by dbssAlan** [mapbox/supercluster#177]
Hi，the result of this method is problematic. When the points are aggregated, there are omissions, which causes some points to disappear.The cause of the error has not been found yet. Has anyone encountered a similar situation? 

"supercluster": "^7.1.3",
"mapbox-gl": "1.13.0",
"react-mapbox-gl": "^5.1.1",

`
let clusterList = index.getClusters(
        [bounds['_sw']['lng'], bounds['_sw']['lat'], bounds['_ne']['lng'], bounds['_ne']['lat']],
        Math.floor(zoom)
);
`

**Comment by mourner** [comment]
Unfortunately there's no way to diagnose a potential issue like this without a reproducible live test case. Will be happy to reopen the issue if you provide one.

**Comment by dbssAlan** [comment]
Thanks! I found the cause of the problem. I passed an aggregation point to this method, which caused the result count to be incorrect. I'm too careless.
