### ISSUE TITLE
Using with Web Mercator

### ISSUE THREAD

**Issue by MikeTheReader** [mapbox/supercluster#18]
I am using this library with point data that is already in web mercator. Currently, I'm converting the points into lat/long.

I see the comments for lngX and latY functions says that they convert "longitude/latitude" to spherical mercator in [0..1] range", but I'm not understanding how I would get a similar 0..1 number directly from web mercator coordinates. Any help on that would be greatly appreciated.

Thanks much.

**Comment by mourner** [comment]
@MikeTheReader 0..1 corresponds to -180..180 longitude range. So if you have mercator meters, you would divide coordinates by the width of the world in meters.
