### ISSUE TITLE
Supercluster to PBF tiles on server side consumed by OpenLayers gives weird results

### ISSUE THREAD

**Issue by AntoJvlt** [mapbox/supercluster#183]
Hello,

I am experiencing a lot of difficulties to generate PBF vector tiles by using Supercluster with node.js on the server side.

I generate clusters with Supercluster from a GeoJSON features list, then I iterate over all the tiles and convert them to PBF file with [vt-pbf](https://github.com/mapbox/vt-pbf) and save them to **directory/{z}/{x}/{y}.pbf**. Then, I serve this folder containing the tiles and consume it on a VectorSource layer with OpenLayers.

Problem is that the resulting features on my OpenLayers map are really weird and wrong. I am suspecting that it can come from wrong extent/projection but since I am still lacking of knowledge on the vector tiles system I really can't find a solution.

I have set up a little prototype that you can check to see the problem:

* The OpenLayers map frontend: https://gsoc2021-qa.nominatim.org/supercluster/
The blue dots are features from a GeoJSON layer using data from a GeoJSON file on the server. The red dots are the features from the VectorTile layer which uses the PBF files from the server. These PBF files were generated as I explained before, the Supercluster.load() input is the list of features from the GeoJSON file which is the same one used for the blue dots layer.

* The very basic React component which creates the map and layers: https://github.com/AntoJvlt/Nominatim-Data-Analyser/blob/supercluster-and-frontend/visualizer/src/components/OLMap.js

* My node.js tool which creates the PBF file with Supercluster and [vt-pbf](https://github.com/mapbox/vt-pbf): 
https://github.com/AntoJvlt/Nominatim-Data-Analyser/blob/supercluster-and-frontend/clustering-vt/index.js
You can check the generate() method to go directly to the point. I read the features list from stdin.

I need to create PBF files for the vector tiles and I am really stuck currently. I tested multiple configurations, multiple extent values but I can't find a working solution.

Thank you very much for your help.

**Comment by mourner** [comment]
Hi @AntoJvlt — while I unfortunately don't have the bandwidth to investigate your setup and find what's wrong there (perhaps StackOverflow would be more appropriate?), you may be able to find some hints from this repo which basically attempts the same thing: https://github.com/chrisloer/supertiler

Closing as this is not a Supercluster issue.
