### ISSUE TITLE
Question: Getting wrong Longitude

### ISSUE THREAD

**Issue by GuangHa** [mapbox/supercluster#184]
I am giving the following 3 locations to cluster.load:
coordinates: Array [ 17.9575397, 102.6318804 ]
coordinates: Array [ 11.5437912, 104.9215138 ]
coordinates: Array [ 13.09573, 103.2022055 ]

But i am getting the cluster with the following coordinates back:
lat: 14.199013710021973
lng: 76.44821493302953

My BBOX setting is [-180, -180, 180, 180].

I've also tried to play around with the longitudes of the locations and it seems that it doesn't get higher than 85 Longitude (The cluster generated with locations longitude lower than 85 are working perfectly fine). Does anyone has an idea what the problem could be?

**Comment by mourner** [comment]
The coordinates should be in `longitude, latitude` order, like in GeoJSON. You have it reversed.
