### ISSUE TITLE
Clustering customization

### ISSUE THREAD

**Issue by MichalNemec** [mapbox/supercluster#187]
Please check this link out! 
https://github.com/maplibre/maplibre-gl-js/issues/429

what im missing from implementation now is the hover to show coverage.
In my case i would be more interested in coverage shown all the time or toggle it off, so ON,OFF,HOVER,CLICK to have all options?

Thanks!

**Comment by mourner** [comment]
You can implement the coverage manually in your app by using the `getChildren` method and generating a convex hull with something like Turf on hover. Supercluster is a minimal library focused on the clustering algorithm and implement UI features like this is out of scope for it.
