### ISSUE TITLE
Markers disappearing - strange cluster/marker behaviour

### ISSUE THREAD

**Issue by simplenotezy** [mapbox/supercluster#195]
We have noticed some of our users experience this weird bug. Notice how markers should be inside a cluster, but they're not, and as user zooms in, the marker disappears. 

![ezgif-6-3e0e85c2aa](https://user-images.githubusercontent.com/3786627/149185546-2c0cc57b-f35c-40aa-a627-01a8acfcc421.gif)

Have anybody experienced it before? I cannot reproduce it myself.

**Comment by simplenotezy** [comment]
I have tried disabling the cluster feature in hopes that it would solve the issue, however, it does not.

It's important to state that the issue does not always occur, it seems random when it does.

![RPReplay_Final1642516376](https://user-images.githubusercontent.com/3786627/149988587-465aa02f-e9c0-4eea-be49-fe983366e6a0.gif)

**Comment by simplenotezy** [comment]
Possibly related:
- https://github.com/mapbox/supercluster/issues/135

**Comment by mourner** [comment]
There's absolutely no way to diagnose this without a minimal live test case. But if it's still reprodible without clustering, there's nothing to do on the Supercluster side in any case.
