### ISSUE TITLE
[Question] Cluster touchable area

### ISSUE THREAD

**Issue by isaac-tcs** [mapbox/supercluster#196]
Hello,
Is there a prop that handles the size of touchable area?
Default touchable area is very wide as shown in my video.

https://user-images.githubusercontent.com/87542877/150894064-db4f56f1-5c56-4b5c-a38a-a0b8e8a733b8.mp4

**Comment by mourner** [comment]
Supercluster only handles the underlying clustering algorithm, it has nothing to do with any interaction or appearance of clusters, so you probably reported this in the wrong repo. Hard to say more without a reproducible live test case — video doesn't load for me, but it's not enough in any case.
