### ISSUE TITLE
choose the weighted center or center?

### ISSUE THREAD

**Issue by sw897** [mapbox/supercluster#2]
Searching for neighbors in rtree use the weighted center. Should build rtree  using  the weighted coordinates either? 
I think the two places should use the same one, weighted center or center.
Maybe the weighted center is better

**Comment by mourner** [comment]
Supercluster uses weighted centers for all calculations. Could you point out a specific part of the code that you don't like?

**Comment by mourner** [comment]
I now see your point. This was addressed as a part of #5.
