### ISSUE TITLE
get all markers in a cluster

### ISSUE THREAD

**Issue by crisfcodes** [mapbox/supercluster#201]
I'm using [superclsuter](https://github.com/mapbox/supercluster) for clustering markers in react native map, what I want is to get all children from a cluster no matter what level of nesting a cluster may have.

to explain the situation a little better, a cluster can have markers and other clusters as children, I need to flatten the child clusters to get markers inside them.

```
cluster
  marker
  cluster(3 markers)

// this should return the 4 markers, the top-level marker, and markers within the child cluster
```

**Comment by cflorez10** [comment]
@mourner any idea how to do this?

**Comment by mourner** [comment]
The method for doing this is called `getLeaves`, you can see the docs for it here: https://github.com/mapbox/supercluster#getleavesclusterid-limit--10-offset--0
