### ISSUE TITLE
Add typescript's definition

### ISSUE THREAD

**Issue by johannchopin** [mapbox/supercluster#203]
Hey team 👋 

Thanks a lot for the work put on this project that I really enjoy. I would enjoy it even more if there was official TypeScript type definition available. Since rollup is already used, it will be straightforward to add the types directly to the repo https://github.com/rollup/plugins/tree/master/packages/typescript. Another approach would be to add a `.d.ts` file to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

I can take care of it if you want 👍

What do you think of this idea?

**Comment by quinn** [comment]
+1 on this. Can authors respond to this? I think 1st class type support should be expected for a commercial product intended to be used in a professional setting.

**Comment by mourner** [comment]
There are pretty high-quality type definitions maintained at DefinitelyTyped, although I do plan to add official types to the project. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/supercluster/index.d.ts

**Comment by quinn** [comment]
Thanks @mourner. Yep, the DefinitelyTyped types are working well for me

**Comment by johannchopin** [comment]
@mourner Can we add this information to the README so that devs know that the `@types/supercluster` package is safe?

**Comment by madiyetov** [comment]
Hey @mourner, the new version of this package and related ones (`kdbush`, `geokdbush`) are not supported in Typescript, right?
