### ISSUE TITLE
Calling supercluster.load(Points) then calling supercluster.getClusters() my arbitrary  properties data are gone

### ISSUE THREAD

**Issue by luan-dang-techlabs** [mapbox/supercluster#207]
Anyone having issue when using supercluster.load(Points), 

e.g. Passing to supercluster.load(Points)

 Points = {
   type: 'Feature',
    properties: {
      hi: 'world,
    }
   geometry: { type: 'Point', coordinates[,,]}
  }

e.g. Getting supercluster.getClusters(bound, 2);

 Points = {
   type: 'Feature',
    properties: {
      cluster_id: z,
      // my data is gone but other properties for supercluster exist
    }
   geometry: { type: 'Point', coordinates[,,]}
  }

**Comment by luan-dang-techlabs** [comment]
I didn't realized I was looking at clusters and not individual non-cluster.

**Comment by luan-dang-techlabs** [comment]
@francescocretti -From what I remember,  clusters: those big blobs  , non-clusters : individual data points. i was trying to find information for individual points but i was looking at the cluster instead. hope that helps.

**Comment by francescocretti** [comment]
@luan-dang-techlabs yes, that was it! thanks :)
