### ISSUE TITLE
how to use supercluster instance methods in different React components

### ISSUE THREAD

**Issue by cflorez10** [mapbox/supercluster#209]
I am using [supercluster](https://github.com/mapbox/supercluster) in a react application, the initialization(`new Supercluster()`) is executed in one component but I need to access the instance methods in other components.

I want to know if sharing the instance through a [react context](https://reactjs.org/docs/context.html) or a [global state management library](https://github.com/pmndrs/zustand) causes performance issues or if there is any drawback with this approach.

@mourner can you shed some light here?

**Comment by mourner** [comment]
Intuitively there should be no performance issues or drawbacks associated with this, but I'm not a React expect — it's best to ask stuff like this in React-focused communities or StackOverflow.
