### ISSUE TITLE
Feature Request: Pass the children of the cluster as an Array to the cluster

### ISSUE THREAD

**Issue by Duderinooo** [mapbox/supercluster#213]
Basically what the title says. I would suggest that the children, whatever I want to cluster, are accessible within the the properties of a cluster. Or is there another way to acces them? I can only see the point count, but not the items in the cluster in the properties.

**Comment by marksmall** [comment]
Is this planned to be release any time soon, if it was completed last week? I've been looking for this feature for a while now. Or can someone state how to achieve this.
