### ISSUE TITLE
supercluster__WEBPACK_IMPORTED_MODULE_4__ is not a constructor

### ISSUE THREAD

**Issue by XardasLord** [mapbox/supercluster#220]
I'm getting this issue in my Angular application when calling the constructor:
```
const index = new Supercluster({
        radius: 60,
        extent: 256,
        maxZoom: 17,
      })
```
```
supercluster__WEBPACK_IMPORTED_MODULE_4__ is not a constructor
```

What is the problem?

**Comment by mourner** [comment]
I don't know — looks like something to do with your Angular/Webpack setup, nothing we could help with on the Supercluster side.
