### ISSUE TITLE
Maplibre-GL-JS Example?

### ISSUE THREAD

**Issue by koufopoulosf** [mapbox/supercluster#228]
Hello,

May I please ask if is there any example implementing this Superclusters functionality for the Maplibre-GL-JS map? I would really appreciate such help🙏

Thank you very much in advance!!

**Comment by mourner** [comment]
It is used there for clustering internally. Here's an example https://maplibre.org/maplibre-gl-js-docs/example/cluster/

**Comment by koufopoulosf** [comment]
Hi @mourner and thanks for your reply.

On the link that you shared, there is a bug with the tranbsition of the text vs the transition of the circles:

![image](https://github.com/mapbox/supercluster/assets/66564413/c6b2a730-4a58-4e61-96a8-196af8c973e4)

I made this Github Issue here as I am looking for those clusters that do NOT seem to have the mentioned issue:

![image](https://github.com/mapbox/supercluster/assets/66564413/ff17cf50-53ba-4fe0-b5db-9d46147410bd)

Any ideas maybe?

Thanks in advance!
