### ISSUE TITLE
Carry generic properties

### ISSUE THREAD

**Issue by JamesRamm** [mapbox/supercluster#23]
I wonder if it is possible to carry the properties for each marker so that you could do a eg a pop-up on each marker/summary pop-up for each cluster

**Comment by bewithjonam** [comment]
By this commit https://github.com/mapbox/supercluster/commit/03746dc06167c447034566d292c92a23afd137a1, we can query for the children in a cluster. When hovering over a cluster, you can query for the children in the cluster and show the popup. 

I had a similar use case and am now using this method. Sample:
https://bewithjonam.github.io/mapboxgl-spiderifier/docs/custom_markers_and_popup.html

**Comment by mourner** [comment]
Yes, a subset of this is possible with the new `getChildren` method, but there's also properties aggregation support (to be implemented) that will extend this, currently tracked in #12.
