### ISSUE TITLE
ESM failure in Next.js + Jest

### ISSUE THREAD

**Issue by samsch** [mapbox/supercluster#233]
```
    import KDBush from 'kdbush';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
This can be reproduced by setting up the default Next.js TypeScript project, following their instructions to setup Jest, creating a test file that imports supercluster, and running `npx jest`.

I made several attempt to force it to work with various TypeScript, Jest, and external workarounds, but was unable to within several hours of work.

---

It looks like the "exports" property in package.json blocks the files in `dist/` from being used, which includes the default "main" entry.

I would recommend changing the exports package.json property to include the `dist/` directory.
The ESM output file should use .mjs, the commonJS output file should use .cjs.

I think that should correctly configure the project to default to CommonJS unless ESM is specifically requested by the importer.

There is also more info available here about an ESM wrapper approach that may be suitable: https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper

**Comment by mourner** [comment]
Supercluster is set up properly and unambiguously as a ESM package. If you have unexpected issues when using it in Next.js with Jest and TypeScript, perhaps it's worth reporting the issue in the respective projects.

> It looks like the "exports" property in package.json blocks the files in dist/ from being used, which includes the default "main" entry.
> I would recommend changing the exports package.json property to include the dist/ directory.

`exports` is intentionally configured to point to `index.js`, the ES module entry. Builds in `dist` are legacy browser builds that aren't supposed to be used in a bundler configuration. `exports` field takes precedence over `main` so it doesn't matter if the latter is present or what it specifies (it's a leftover for legacy Node versions) — see the docs.

> The ESM output file should use .mjs, the commonJS output file should use .cjs.

Not if the `package.json` has `type: "module"` specified, in which case all `.js` files are treated as ESM.

> I think that should correctly configure the project to default to CommonJS unless ESM is specifically requested by the importer.

This project is ESM only. CommonJS support was intentionally dropped in v8.0.0, and is no longer available.

**Comment by riorafe** [comment]
Experience this same error also

**Comment by riorafe** [comment]
This happen when using
`babel-jest: "29.6.4"`
`jest: "29.5.0"`

and upgrade supercluster to version 8.0.0

The babel-jest and jest version is alright if we use supercluster 7.1.5

**Comment by riorafe** [comment]
I managed to resolve this issue by adding supercluster and kdbush in transformIgnorePatterns at jest.config.js
![image](https://github.com/mapbox/supercluster/assets/46643712/297dcafe-602e-4864-a51a-4c8d020c4596)

Hope it helps!

**Comment by jwasilgeo** [comment]
That did the trick and was perfect for my needs, thanks @riorafe.
