### ISSUE TITLE
Not support type script (Nestjs)

### ISSUE THREAD

**Issue by CHOMNANP** [mapbox/supercluster#235]
I tried import and using the library above in Nestjs.

Yet, look like it not supported.

![Screen Shot 2023-08-18 at 10 59 27 AM](https://github.com/mapbox/supercluster/assets/5925050/3a627311-a3d7-46ef-bd01-52190a1160c4)

**Comment by danieltyukov** [comment]
Same problem, I believe this should be addressed ASAP. The plugin is not compatable with NestJS

**Comment by mourner** [comment]
Supercluster does not support CommonJS environments since v8. Either use a ES Modules-based setup (or report an issue about this to Nest), or use an older version of Supercluster.

**Comment by danieltyukov** [comment]
> Supercluster does not support CommonJS environments since v8. Either use a ES Modules-based setup (or report an issue about this to Nest), or use an older version of Supercluster.

Since which version did did supercluster stop supporting CommonJS so we can install an older version of the package?
