### ISSUE TITLE
Dynamic filtering of data without reinitializing cluster

### ISSUE THREAD

**Issue by at-cf** [mapbox/supercluster#238]
I'm clustering millions of rows and using the supercluster reduce function to aggregate stuff. My users want to be able to filter the data on the fly. Now I'm re-initing a whole new Supercluster on every filter change. It would be really cool if you could add a filter function as an argument to the getClusters call. If that's not possible, what's the correct approach for this use case?

**Comment by grundmanise** [comment]
Hi @at-cf, I have a similar use-case. What solution did you end up with?
