### ISSUE TITLE
Question:  does clusterRadius value represent miles, meters, yards, etc? 

### ISSUE THREAD

**Issue by hmendezm** [mapbox/supercluster#240]
I try to figure out is the cluster radius is miles or some other measure unit. I have read in some places radius is in pixels and others in square miles.

Best
H. Mendez

**Comment by mourner** [comment]
It's in the readme.

<img width="648" alt="image" src="https://github.com/mapbox/supercluster/assets/25395/9a66af45-88b2-466a-b4f0-21e6f9f827f6">

**Comment by vitiaaap29** [comment]
Can I calculate cluster radius in meters based on radius and extent?
