### ISSUE TITLE
Question: How do I cluster specific markers

### ISSUE THREAD

**Issue by SergueySHD** [mapbox/supercluster#242]
I know it's not the place to ask questions, but...

Is there a way to cluster specific markers together? Let's say I've got 3 markers, 2 of them have a property that has the same value whilst the third one doesn't. I want to cluster those 2 markers, but not the third one. But if I would introduce a fourth one that shares a value with the third marker, I would want to cluster those 2 together.
Is this something that can be done using the reduce function? All markers come from a different source (but are in the same feature array when passed to supercluster)

Thanks in advance!

**Comment by cscetbon** [comment]
That's something I'd like to know as well. @SergueySHD did you find a way ?

**Comment by cscetbon** [comment]
@mourner can you answer that question ?

**Comment by SergueySHD** [comment]
@cscetbon The way I got around this for our use case is by using multiple supercluster instances per "cluster group" instead of 1 and remaking them on map move, because we fetch our markers depending on the current viewbox. I loop over all of the markers and depending on the source I group them in different arrays to create the supercluster instances.

I did do some performance testing and it took about 5-20ms to process all of the visible markers on the screen (at some point there were thousands), so it's fine to keep remaking the instances.

**Comment by cscetbon** [comment]
And what do you then do with those different clusters ? I was thinking it could help me draw a heatmap of temperatures by grouping them in different clusters but I'm not sure. A regular heatmap uses density but I want to use values for the color instead

**Comment by SergueySHD** [comment]
I don't think clustering them would be the best solution from a visual standpoint. 
Our use case was to cluster different modes of transportation that belong to a certain group (e.g. shared bikes vs car related stuff).
