### ISSUE TITLE
missing file supercluster.js

### ISSUE THREAD

**Issue by evejweinberg** [mapbox/supercluster#25]
I'm running the demo and I'm missing the file supercluster.js. Can you post that, or do you know why I'm getting that error? This was after 'npm install'
Thanks! Excited to get this working!

**Comment by apkoponen** [comment]
There is a (pretty well hidden) comment in the worker.js file that helps, attached below. I had the same issue.

```
// generate supercluster.js from the repo root with:
// browserify index.js -s supercluster > demo/supercluster.js
```

So, just run `browserify index.js -s supercluster > demo/supercluster.js` in the folder where you cloned the repository.

**Comment by maxvonhippel** [comment]
Any chance we could get that comment added to the README?  I think it's fair to say that for most users that is a pretty essential "installation" step since most of us probably just build off the demo.

**Comment by apkoponen** [comment]
I'm no a maintainer in this project, but I would guess a PR is always welcome.
