### ISSUE TITLE
Filter?

### ISSUE THREAD

**Issue by but1head** [mapbox/supercluster#26]
Hello. Awesome cluster, thank you!
I have a trouble... How to filter points?

All points have "test": (1-5) in "properties";

**Comment by mourner** [comment]
Can you explain what you mean by filtering? Do you want to filter the points _prior_ to generating clusters? Or do you want to filter the view dynamically, adjusting cluster numbers? I think the former is better achieved by filtering the data prior to giving it to supercluster, and the latter is not technically possible.
