### ISSUE TITLE
Where's trees-na.json?

### ISSUE THREAD

**Issue by psolbach** [mapbox/supercluster#3]
Hi Vladimir – fired up the demo, where do I find the trees-na.json?
Am I supposed to put my own data in there? Don't have 40 megs worth of point data
lying around atm :)

**Comment by Matheo13** [comment]
Hi, same question.
It's also steel a bit unclear for me, can we use it without MapBox?
And do you plan to make a selection system? And it is possible with your index system?
Something like that? 
http://recordit.co/cFXNDI9DhI
(based on https://github.com/Leaflet/Leaflet.markercluster)
Maybe I should make an other question issue?
Thank you!

**Comment by Bob404** [comment]
Hi Vladimir.
Same question here too!
Sorry if I missed something.

**Comment by JatGitHub** [comment]
Some explanation would be nice indeed.

**Comment by mourner** [comment]
It's just a sample GeoJSON file with 400k point features that I don't want to commit to the repo because it's a 40MB file. I'll think about making the demo more approachable...

**Comment by psolbach** [comment]
Cool, I'll find something.
