### ISSUE TITLE
How can supercluster be integrated with Mapbox-GL-JS?

### ISSUE THREAD

**Issue by mushon** [mapbox/supercluster#34]
And if it can't how can we take advantage of similarly advanced clustering features in mapbox.gl.js?

**Comment by mourner** [comment]
Supercluster is already integrated into Mapbox GL JS — it is the library that gives it its clustering features.

**Comment by mushon** [comment]
Oh, I see, thanks @mourner
In that case I guess the features I am missing are not currently supported by SuperCluster and are only supported by Leaflet's clustering. Specifically what I'm missing is [Multiple differently styled clusters](https://www.mapbox.com/mapbox.js/example/v1.0.0/markercluster-multiple-groups/) and [Listing markers in clusters](https://www.mapbox.com/mapbox.js/example/v1.0.0/listing-marker-clusters/)

**Comment by mourner** [comment]
@mushon you can create multiple clustered GeoJSON sources and style them differently already. As for listing markers in clusters, I'm working on this and it'll be available soon — see https://github.com/mapbox/supercluster/pull/32

**Comment by mushon** [comment]
Ok, I'll look into that. And what about declustering markers placed on the exact same geolocation. Is the star declustering feature available in Supercluster too?
![star declustering](http://g.recordit.co/PO5FssoB2P.gif)

**Comment by foundryspatial-duncan** [comment]
Once we can get the cluster members from some method in Mapbox GL (getLeaves, or whatever it will be), we'll have everything we need to manually do that decluster effect (used to be called "spiderfying," I think). I'm anxiously awaiting the addition of these supercluster methods in the Mapbox GL API :)

**Comment by MathewJuma** [comment]
@mourner thanks for the support you have given on this. I am using the Superclustering class and not able to pool the info tooltip on a marker. Can't also find any documentations. Can you help please?

**Comment by thuanmb** [comment]
For ReactJS lover, here is a solution for clustering (using supercluster) in mapbox-gl:
https://github.com/thuanmb/react-mapbox-gl-cluster

**Comment by maufarinelli** [comment]
Do you guys have an example of how to get the cluster and use all superclusters available methods (`getClusters(bbox, zoom), getTile(z, x, y), getClusterExpansionZoom(clusterId)`) in Mapbox GL?
The only example I found of clusters is: 
https://www.mapbox.com/mapbox-gl-js/example/cluster/
and it does not any use of superclusters methods.
Thanks guys

**Comment by mourner** [comment]
Hey @maufarinelli, the integration is coming in https://github.com/mapbox/mapbox-gl-js/pull/6829, which also includes an example. Check it out!

**Comment by maufarinelli** [comment]
AMAZING @mourner . Thanks you so much
