### ISSUE TITLE
Unexpected clustering result

### ISSUE THREAD

**Issue by amiiit** [mapbox/supercluster#35]
I'm experiencing a strange behaviour of 'disappearing' markers on my map when wrapping my markers with `supercluster`:

![jan-28-2017 11-07-08](https://cloud.githubusercontent.com/assets/2736813/22395837/23440dbe-e54a-11e6-8741-03209b879555.gif)

I managed to boil down the error to that: (jest syntax)

```
import supercluster from 'supercluster' // 2.2.0

test('get clusters', () => {
    const index = supercluster({
        radius: 40,
        maxZoom: 16
    })

    index.load([{
        geometry: {
            coordinates: [76, 17.7]
        }
    }])

    let clusters

    clusters = index.getClusters([18,-61,83,162], 1)
    expect(clusters.length).toBe(1) // as expected

    clusters = index.getClusters([18,-61,83,162.3], 1) // slightly different borders
    expect(clusters.length).toBe(1) // fails, clusters length === 0

});

```

I suspect a rounding error due to the following observations:

1. Changing just one of the border components from `162` to `162.3` causes this unexpected behaviour
2. Rounding down the coordinate `[76, 17.7]` to `[76, 17]` returns one cluster element as expected in both test cases

Or am I doing something wrong here?

**Comment by amiiit** [comment]
Just tested against master with the same result

**Comment by mourner** [comment]
Hmm, could it be caused by the invalid latitude values? They typically range from -85 to 85 for the Mercator projection used in Supercluster, and in your example, they're `162` and `162.3`. Does the bug disappear when bounding the latitude values by -85..85?

**Comment by mourner** [comment]
Yeah, just checked and the problem is that latitudes not in -90..90 range are invalid. It should work consistently with the valid range.

**Comment by amiiit** [comment]
Apparently my map boundaries and points had the wrong order for `[lat, lng]`.

Thanks for the help!

**Comment by seleckis** [comment]
I have the same issue. getClusters returns empty array when westLng reaches 180 and eastLng reaches -180. E.g. between [174, 8, -56, 55] and [56, 8, -174, 55] — no result. I use google maps, may be the bound which google maps api passes are not in the format as supercluster expected?

**Comment by seleckis** [comment]
I've got. Leaflet which is used in example produces this kind of bounds:
`[56, 8, 174, 55], [174, 8, 292, 55] or [-62, 8, 56, 55], [-182, 8, -64, 55].` So west lng is always lower then east lng.

Google maps produces values only between -180 and 180, so when west lng is higher then east lng, markers does not return. I made a temporary solution for my project:

this is a method which I use in my app, and it runs every time map changes props (zoom, drag, etc.):
```js
getClusters = ({ zoom, bounds}) => {
	const {sw, ne} = bounds;
	const bbox = [sw.lng, sw.lat, ne.lng, ne.lat];

	let clusters = [];
	if (sw.lng > ne.lng) {
		// here we need to get clusters two times: when there are negative values and positive ones.
		bbox[0] = sw.lng - 360;
		clusters = this.supercluster.getClusters(bbox, zoom);
		bbox[0] = sw.lng;
		bbox[2] = ne.lng + 360;
		clusters = clusters.concat(this.supercluster.getClusters(bbox, zoom));
	} else {
		clusters = this.supercluster.getClusters(bbox, zoom);
	}

	return clusters;
}
```
