### ISSUE TITLE
Geojson Example

### ISSUE THREAD

**Issue by JSMap** [mapbox/supercluster#4]
Hi,
Can you share your ('../trees-na.json') in Demo file , please ?
I need to show this file because with my geojson, your demo doesn't work.
Thank you

**Comment by mourner** [comment]
Ah, I think this is a mistake in the demo code that causes confusion — it expects an array of GeoJSON features rather than a GeoJSON feature collection. Should be an easy change on the demo side, and I'll look into adding a small GeoJSON sample to the repo.

**Comment by simison** [comment]
@mourner Perhaps add a script that would generate n amount of markers?

**Comment by mourner** [comment]
@simison maybe, but I don't like generating random points because it's not representative of how it'll look on real data.

**Comment by simison** [comment]
That's cool. I actually have a small script that generates more realistic
data. See:
https://github.com/Trustroots/trustroots/blob/master/scripts/fillTestData.js

It tries to position them around cities, on land.

**Comment by Geocloud** [comment]
Ok Lets me know when your issue is resolved

**Comment by mourner** [comment]
@simison that's a neat idea! I did clustered data generation for my [RBush demo](http://mourner.github.io/rbush/viz/viz-cluster.html), but generating random points clustered around real cities seems even nicer.

**Comment by mourner** [comment]
I pointed the demo to a small GeoJSON test fixture in the repo for now, so it should work out of the box now. Will consider using more points or generated data for later.
