### ISSUE TITLE
Custom polygon appearance

### ISSUE THREAD

**Issue by dayAlone** [mapbox/supercluster#40]
Do mapbox-gl with supercluster have any options to implement [this example](https://www.mapbox.com/mapbox.js/example/v1.0.0/markercluster-custom-polygon-appearance/)?

I need to group points depends on their countries.

**Comment by mourner** [comment]
1. The example you linked to does not group points based on countries, so I don't understand why it's related.
2. Supercluster is not going to support grouping by polygons. You'll have to manually preprocess the data into separate sets, e.g. with TurfJS.
