### ISSUE TITLE
Optimize supercluster to work correctly with google maps

### ISSUE THREAD

**Issue by seleckis** [mapbox/supercluster#41]
I use supercluster with google maps. Everything works as expected except two situations:
1) Google maps returns bounding box from -180 to 180, so when on the map we see e.g. Pacific ocean the lngs of bbox will be e.g. from 100 to -100. In this case supercluster will return nothing. As I mentioned [here](https://github.com/mapbox/supercluster/issues/35#issuecomment-282520081) I reed from 100 to 180, and then from -180 to -100 to get the correct result.
2) Same Issue if google map has zoom level 1 or 2 when it starts to repeat. In this case we have lngs of bbox e.g. from -180 to e.g. -170. So we see more then 360deg wide map, but supercluster will read only those 10 degrees.

![map](https://cloud.githubusercontent.com/assets/988504/23546753/bd982632-0009-11e7-9d0e-5b2b340e380f.png)

Sorry I cannot make a public example right now.

**Comment by mourner** [comment]
I think cases like this should be handled on the application side rather than in supercluster, as they're specific to the API you're using to display the clusters. E.g. for this particular case, you would have to split the bounds into valid ranges (say, 170..180, -180..180, -180..-170), and merge the features from the queries.

**Comment by seleckis** [comment]
I tried to split those, but the position of clusters and markers received from supercluster.getClusters are not correct. They are correct only when center.lng = 0. When I drag the map, clusters are flowing. It seems this is due to incorrect bounding box. The last renge in your example (-180..-170) is in the same range as your second range (-180 — 180).

**Comment by mourner** [comment]
Unfortunately I don't have the bandwidth to debug and fix your application for you. If you can make a minimal, specific test case that can prove that positions from `getClusters` are not correct, feel free to open a new issue. 

> The last range in your example (-180..-170) is in the same scope as your second range (-180 — 180).

The world wraps, so both ranges on the left and right will be a part of the -180..180 range, they will just be shifted by 360 degrees either way.

**Comment by badalrocks** [comment]
@seleckis could you share the sample code of using supercluster with google maps? I am working on it but cannot find examples online.

**Comment by seleckis** [comment]
@badalrocks, unfortunately, I cannot due to NDA. But I can share a function that I used to get clusters in a way I have mentioned:
```js
const getClusters = ({ zoom, bounds}, markers) => {
    const {sw, ne} = bounds;
    const bbox = [sw.lng, sw.lat, ne.lng, ne.lat];

    const filteredMarkers = markers.filter((marker) => !marker.isHidden);
    supercluster.load(filteredMarkers);
    supercluster.load(markers);

    let clusters = [];
    if (sw.lng > ne.lng) {
        bbox[2] = 180;
        clusters = supercluster.getClusters(bbox, zoom);
        bbox[0] = -180;
        bbox[2] = ne.lng;
        clusters = clusters.concat(supercluster.getClusters(bbox, zoom));
    } else {
        clusters = supercluster.getClusters(bbox, zoom);
    }
    return clusters;
}
```

**Comment by badalrocks** [comment]
I found 2 solutions to this problem of showing too many points (features) on Google maps. I will post sample code for both of them.

1. **Using Supercluster library** (https://github.com/mapbox/supercluster):
Below code does the following:
a. Gets bounding box of the map.
b. Create clusters using supercluster library. 
c. Iterate through the clusters, determine if item is cluster or individual feature, and add appropriate marker on the map.
d. addCluster() does the job of creating cluster marker.

    <code>
            // get bounding box. gmap is native Google Maps Javascript object.

            let bounds: LatLngBounds = this.gmap.getBounds();
            let northEast: LatLng = bounds.getNorthEast();
            let southWest: LatLng = bounds.getSouthWest();
            
            // cluster GeoJSON points
            var index = this.supercluster.load(this.mapData["features"]);
            
            // first parameter is the bounding box. but it can be hard-coded for testing.
            var clusters = index.getClusters(
                      [southWest.lng(), southWest.lat(), northEast.lng(), northEast.lat()],
                      this.gmap.zoom
                    );
            
            // symbol to show on the map for individual feature (not-cluster)
             var arrow = {
                      path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
                      fillColor: "red",
                      fillOpacity: 0.7,
                      scale: 4,
                      strokeWeight: 0
                    };
            
                    for (let cluster of clusters) {
                      let isCluster = cluster.properties.hasOwnProperty("cluster");
            
                      if (isCluster) {
                        let marker = this.addClusterMarker(cluster);
                        this.markers.push(marker); // this.markers is a class level object to keep track of all the markers.
                      } else {
                        var latLng = new google.maps.LatLng(
                          cluster.geometry.coordinates[1],
                          cluster.geometry.coordinates[0]
                        );
                        var marker = new google.maps.Marker({
                          icon: arrow, // if not cluster
                          position: latLng,
                          map: this.gmap
                        });
            
                        this.markers.push(marker);
                      }
                    }
        
          addClusterMarker(cluster) {
            var latLng = new google.maps.LatLng(
              cluster.geometry.coordinates[1],
              cluster.geometry.coordinates[0]
            );
        
            var marker = new google.maps.Marker({
              //icon: "",
              position: latLng,
              label: cluster.properties.point_count_abbreviated + "",
              map: this.gmap
            });
        
            marker.addListener("click", () => {
              console.log(
                "inside click listener marker pos: ",
                marker.getPosition().lat(),
                marker.getPosition().lng()
              );
              let zoomCluster = this.supercluster.getClusterExpansionZoom(
                cluster.properties.cluster_id
              );
              console.log("inside click listener latLng: ", latLng.lat(), latLng.lng());
              this.gmap.setCenter(latLng);
              this.gmap.setZoom(zoomCluster + 1);
              
              );
            });
        
            return marker;
        
          }
    </code>

You'd have to call this logic on zoom change and dragEnd event to get updated clusters. 

Although this works, there is lot of code to be written to handle it. 2nd solution is much cleaner as it is provided out of box by Google Maps API.

2. **Google Maps - MarkerClusterer**. 
Below code does the following:
a. Install MarkerClusterer library. I installed via npm. See this article for installation: https://medium.com/@s.delecroix/how-to-use-markercluster-with-googlemap-in-an-angular-app-9b955e669399
b. updateCluster() does the job of clustering. It first removes any existing markers. Then gets all the markers to be clustered in a markers array. The last line does the magic of creating clusters based on the markers array.

    <code>
    
             mc: MarkerClusterer;
              mcOptions = {
                gridSize: 50,
                maxZoom: 12,
                minimumClusterSize: 25,
                imagePath: "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m"    
              };
            
              arrow = {
                path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
                fillColor: "red",
                fillOpacity: 0.7,
                scale: 4,
                strokeWeight: 0
              };
            
            updateClusters() {
                // remove existing markers from map.
                this.markers.forEach(function(marker) {
                  marker.setMap(null);
                });
            
                if (this.mc) {
                  this.mc.clearMarkers();
                }
            
                this.markers = [];
            
                this.markers = this.mapData["features"].map(entry => {
                  let marker = new google.maps.Marker({
                    icon: this.arrow,
                    position: {
                      lat: entry.geometry.coordinates[1],
                      lng: entry.geometry.coordinates[0]
                    }
                  });
            
                // marker clusterer to manage the markers. magic happens here.
        // map is native Google Maps Javascript object.
                this.mc = new MarkerClusterer(this.map, this.markers, this.mcOptions);
              }
    </code>

I went with 2nd approach. Hope this helps!

**Comment by harrington101** [comment]
@badalrocks I like this, however I'm not familiar with the syntax js: markerclusterer. I'm used to seeing the colon as part of an object but it appears this is not art of an object. Am I missing something?
