### ISSUE TITLE
Can't access cluster leaves

### ISSUE THREAD

**Issue by jzzfs** [mapbox/supercluster#46]
Hey. Thanks a lot for your awesome script.

Here's my issue:

- **Log:** TypeError: Cannot read property 'cluster' of undefined at SuperCluster._appendLeaves (https://unpkg.com/supercluster@2.3.0/dist/supercluster.js:153:22)

- **Codepen:** https://codepen.io/jzzfs/pen/ybavpE 

- **Intention:** I want to retrieve all markers / marker indexes belonging to a cluster after a certain zoom level (>= 16).

- **Problem:** Doesn't matter if I call _getLeaves_ or _getChildren_ -- the response is always some kind of an error. I declare the supercluster on line 125 and pass a supercluster-based index and a valid zoom on line 5298.

- **Testing:** Click your way through the clusters until they disappear and individual markers are shown and observe the log. (might need to use the devtools log because some log entries are too long for the codepen console)

_Related question: is there a way to access the LatLng bounds of a cluster?_ 

Many thanks in advance!
/cc @mourner

**Comment by jameslin123** [comment]
Looking into the 'getLeaves' method, it expects a 'properties' field for every child:

```
var props = children[i].properties;
 if (props.cluster) { ...
```

But a leaf child doesn't get initialized with the "properties" field, so props.cluster would error out.

Perhaps the proper fix is to create such a field for the 'points' inside the index loader.

As a workaround, we can mock that field in the "points" array which we feed to index.load():

```
const points = items.map(
            (item) => {
                return {
                    geometry: item.geometry,
                    item: item,

                    // Workaround: getLeaves expects this field for a leaf node.
                    properties: {
                        cluster: false
                    }
                };
            });

 index.load(points);
```
The getLeaves method returns leaf nodes with this workaround.

**Comment by jzzfs** [comment]
@jameslin123 thank you! This solved my problem.
