### ISSUE TITLE
[Suggestion] add the input validation function

### ISSUE THREAD

**Issue by aaronisme** [mapbox/supercluster#51]
Thanks for this great module. it is quite helpful for my google map. 

`Suggestion`: I am suggesting to add a input validation function to validate the input points are all GEOJSON.feature object.

`Why`: I saw the in readme. it have said it the points should be an array of GEOJSON.feature objects.
>Loads an array of GeoJSON.Feature objects. Each feature's geometry must be a GeoJSON.Point. Once loaded, index is immutable.

but for some people who are not quite familiar with GEOJSON.feature object(just like me), it may have some problems. because I am missing the `properties` field for each point, the `load` function and `getClusters` function still work, but today when I use the `getLeaves` function, it failed. because the points didn't have properties field

```
var props = children[i].properties;
```
 So I am suggesting add the input validation function. throw a error if the input points are not valid GEOJSON.feature object

if you are ok with that, I can open a PR for it:)

**Comment by mourner** [comment]
I just fixed the `getLeaves` problem (see https://github.com/mapbox/supercluster/commit/a8ea1d97940171d3b517d9af23168db0b2dfa775), so this is no longer necessary. Note that a feature with `properties: null` is still a valid GeoJSON feature, it was just treated incorrectly on the supercluster side.
