### ISSUE TITLE
Incorrect cluster location

### ISSUE THREAD

**Issue by tonai** [mapbox/supercluster#52]
Hello,
I have a case where 3 points, which are located near Sydney, are clusterd together with cluster coordinates located in south Africa.
I give you a simple example : https://codepen.io/tonai/pen/weLgvq?editors=0010
The longitude should be about 150 but is actually about 30, and I don't understand why...
Can you help me with that problem ?
Thanks,

**Comment by tonai** [comment]
Latitude and longitude were inverted

**Comment by francoro** [comment]
iIs okay in that order? [westLng, southLat, eastLng, northLat] = SWLng, SWLat,NELng,NELat ?
The second is what returns me google maps from get bounds. I have that doubt

**Comment by tonai** [comment]
I inverted lat ang lng in the list of point.
I wrote [lat, lng] (like in Gmap) instead of [lng, lat].
The codepen has been corrected.

**Comment by oldo** [comment]
Brilliant! I had exactly the same issue - even with trying to show clusters in Sydney and finding them off the coast of South Africa 😊 
Same cause - lat and lng were inverted on the marker components
