### ISSUE TITLE
Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by zhaohongda1987** [mapbox/supercluster#53]
![image](https://user-images.githubusercontent.com/19568031/28904465-b4972c5c-783d-11e7-88fd-1c0038a5013d.png)
supercluster.min.js:1 Uncaught TypeError: Cannot read property 'range' of undefined
    at e.getClusters (supercluster.min.js:1)

Someone knows how to solve it? thanks

**Comment by zhaohongda1987** [comment]
@mourner

**Comment by mourner** [comment]
Can you set up a minimal test case to reproduce this? I haven't seen that error.

**Comment by zhaohongda1987** [comment]
@mourner thank you for your reply, i found the problem is i do not import the module of kdbush

**Comment by mourner** [comment]
Hmm but it should be a part of `supercluster.min.js`, right? Closing this issue, but I still don't quite understand how that error happened.

**Comment by zhaohongda1987** [comment]
@mourner yeah,kdbush is a part of supercluaster.min.js but it not works, so i try to build supercluster.min.js by myself.

**Comment by simison** [comment]
@zhaohongda1987 did you use `npm run build-min` to build that minified version that failed?

**Comment by zhaohongda1987** [comment]
@simison i success to build by the command of npm run build-min, maybe your npm environment has something wrong.

**Comment by skokenes** [comment]
I am getting this error as well...weird scenario though, it only happens at a certain zoom level.

I have about 50k points loaded in. If I do

`index.getClusters([-151.04092284977196, -55.88817699634884, 160.36802048331452, 70.02864384598615],2)` it works fine.

But if I do any zoom level below 2, like say 1.5, it gives me this range error.

Any thoughts?

**Comment by skokenes** [comment]
NVM I just read the documentation -> integer zoom. Sheesh thats embarrassing. Sorry for the spam
