### ISSUE TITLE
Weight attribute

### ISSUE THREAD

**Issue by nicolas-f** [mapbox/supercluster#54]
Hi,

Have you an idea in order to implement a weight attribute ?

Currently all items have a weight of 1 (Add 1 to cluster count).

I have some pre-clustering layers(for each zoom level) on a server side with each feature contains the count of included smallest features.

Could we specify an attribute to read in order to increase the count for each feature ?

```js
    index = supercluster({
        log: true,
        radius: 60,
        extent: 256,
        maxZoom: 17
}).load(geojson.features, 'measure_count');
```
So super cluster would read `feature.properties.measure_count` if the property is not found then it fallback by default to 1 increment to point_count.

The project prune cluster has this weight feature https://github.com/SINTEF-9012/PruneCluster

Thanks

**Comment by mourner** [comment]
This can be implemented using the new map/reduce feature: #36. It's not yet documented though — I need to expose it in the readme.
