### ISSUE TITLE
Getting the bounds of a cluster?

### ISSUE THREAD

**Issue by skokenes** [mapbox/supercluster#56]
Hi, my understanding of kdbush is that it groups the points into rectangular areas using median lines. If that is the case, is there anyway for a given cluster to get the bounding box of lat/long for the points it represents?

Here is an example use-case I am working on where this would be helpful:
I have a server-side data source with 50k geopoints that have various metrics associated with them. I pull those 50k points down client side and render them onto a map using supercluster. I now want to implement a details-on-demand mechanism when a user hovers a cluster. Specifically, when hovering a single cluster, I want to show a tooltip with additional, dynamically calculated data about the points within that cluster. To get this calculated data, I need to run a new query against my data source, but only for the points contained within this cluster.

Today, the way I am doing this is by getting all of the children points of the cluster and creating a query with them. This can create an excessive query if you have lots of points and is not the most performant solution. If I had the bounding box that contains the points instead, I could run a smaller and faster query that uses the lat/lng ranges to filter to the appropriate points, rather than having to ship a query with a list of every point in my cluster.

**Comment by skokenes** [comment]
I guess I could do this myself with something like `turf.bbox`, but just wondering if internally supercluster can already easily return a bbox range so I don't have to take on additional performance hits for calculating a bbox around a large list of features

**Comment by skokenes** [comment]
From further investigation, it looks like the points behind a cluster do not fit into a box that doesn't intersect the bbox of other clusters. Is that correct? If so, it looks like I'll have to go with querying with a list of points within the cluster.

**Comment by mourner** [comment]
> From further investigation, it looks like the points behind a cluster do not fit into a box that doesn't intersect the bbox of other clusters. Is that correct?

Yes, that's correct. I think querying with `getLeaves` is OK if your cluster isn't too big.
