### ISSUE TITLE
Use supercluster without GeoJson

### ISSUE THREAD

**Issue by Stavroswd** [mapbox/supercluster#57]
#Hey guys, 

is there a way to use the supercluster without GeoJson? 
Meaning i just use all my mapbox-gl marker objects. 

thanks, 
Stav

**Comment by mourner** [comment]
Unfortunately no.

**Comment by Stavroswd** [comment]
Ok. 
Do you know an other way to create a cluster or a way to convert the markers GeoJson?

**Comment by sebastianovide** [comment]
If you have your points in markers then you could use lodash for example : geojsonFeatures = _.map(markers, (marker, Id) => ({ ... etc ....
