### ISSUE TITLE
GeoJSON spec links appear to be obsolete

### ISSUE THREAD

**Issue by SimonEast** [mapbox/supercluster#63]
Reading through your README and noticed the links to GeoJSON specs are now obsolete and the page appears to be partially broken. Are there more up-to-date links for these?

Example: http://geojson.org/geojson-spec.html#point

**Comment by sgillies** [comment]
@SimonEast https://tools.ietf.org/html/rfc7946 is the official link for GeoJSON.

**Comment by SimonEast** [comment]
Cheers! Thanks for updating that. 😊
