### ISSUE TITLE
Clustering loading all the points data at a time

### ISSUE THREAD

**Issue by damodhar22** [mapbox/supercluster#64]
Currently we need to add all the coordinates at time in the source on which clustering is performed depending on the zoom level. Here we have a security problem, these coordinates are our critical data we don't want to expose all the data in single api call and load it into the source,which may lead others to get access to all this data in simple call. Is there any general practice to avoid this. Rather than loading all the data at time and  perform clustering on that. I want to load aggregated data points i.e clustered data points depending on the zoom level and bounds,only certain level of zoom in will show the real coordinates of the data points, so that I don't have to reveal all my coordinates in single call.

**Comment by mourner** [comment]
No. The only way to protect your data is to cluster on the server side to generate tiles. I'm working on a CLI tool to make it easier.
