### ISSUE TITLE
How can I use getClusterExpansionZoom?

### ISSUE THREAD

**Issue by mazing** [mapbox/supercluster#65]
I have found `getClusterExpansionZoom` in the documentation.

I know how to use it, but it only returns a zoom level, so what can I use it for?

I guess I will have to translate the zoom level to `latitudeDelta` and `longitudeDelta` if used with Google Maps, but how is this done and how can I get `latitude` and `longitude`?

Is `getClusterExpansionZoom` returning the zoom level given that `latitude` and `longitude` are specified at the current `latitude` and `longitude` of the cluster?

**Comment by mourner** [comment]
`getClusterExpansionZoom` returns zoom level value for a particular cluster. Combined with that cluster's coordinates (longitude and latitude), you can "zoom in" to that cluster so that it expands.

**Comment by brianlaw033** [comment]
but in google map we need latitudeDelta and longitudeDelta, any idea how to convert zoomLevel to them?
