### ISSUE TITLE
Java implementation of supercluster

### ISSUE THREAD

**Issue by debjitk** [mapbox/supercluster#68]
Not a bug specifically. Is there any Java implementation of the supercluster algorithm ?

**Comment by mourner** [comment]
I'm not aware of a Java port currently, but I'd be happy to see one.

**Comment by utahemre** [comment]
This is very late answer but I am using Java implementation of this code. 
You can find this implementation in https://github.com/utahemre/JavaSuperCluster
It might be useful to others
