### ISSUE TITLE
How to add different icons for markers?

### ISSUE THREAD

**Issue by PriyeshT** [mapbox/supercluster#70]
Thanks a lot for this super cool plugin.

I have a question regarding adding custom icons for markers in a cluster.
Currently, it loads the default marker icon that comes along with leaflet. 

How can we add our own custom icons for the markers? The createClusterIcon method in the demo specifies an iconUrl property. I changed it to another image URL, but it still displays the default icon.

I have 4 different types of markers and depending on the type of marker I need to assign it a specific marker icon.

**Comment by mourner** [comment]
Please use issues in this repo to report actual issues with the Supercluster library, not to ask for help with your app. I see that this is Leaflet-specific question, so you could try StackOverflow instead.
