### ISSUE TITLE
getLeaves returns 'No cluster with the specified id'

### ISSUE THREAD

**Issue by KentDi808** [mapbox/supercluster#72]
I am using react-mapbox-gl@3.4.1 and supercluster@3.0.2 to get the list of features in a clicked cluster.

I saw that in V3.0.0 of supercluster the zoom factor is encoded into the cluster_id.

I am using a GeoJSONLayer to do the clustering (which may not be the right way to do it for supercluster) and the correct features are not returned OnClick.

Clicking some clusters throws a run-time error:

> 'No cluster with the specified id'.

Any idea why no features or the wrong features are being returned?

[WebpackBin](https://www.webpackbin.com/bins/-L2LNhHtONvYql3SvYHI) Showing a working example of the issue.

Any help would be appreciated.

**Comment by KentDi808** [comment]
I have come up with a solution that gets me the data that I need.

Modifying the onClick to encode the cluster_id gets all of the items in the cluster.

`  onClick (evt) {
    const map = evt.target;
    const features = map.queryRenderedFeatures(evt.point, { layers: ['clustered_layer'] });
    
    if(!features.length) {
      return;
    }
    const feature = features[0];
    const zoom = Math.floor(map.getZoom());
    const id = feature.properties.cluster_id;
    const cluster_id = (id << 5) + (zoom + 1);
    const all_features = cluster.getLeaves(cluster_id, 500);
    console.log(all_features);
  }`

**Comment by mourner** [comment]
The Webpack bin isn't loading for me for some reason... I'd guess that you're experiencing this issue because GL JS still uses Supercluster 2.3.0, which doesn't encode zoom into ids. We should upgrade there. Let's close here since it's not directly a supercluster issue.

**Comment by KentDi808** [comment]
I'm okay with closing it. For some reason if you do a hard refresh the WebpackBin it will render correctly. Also, thanks for the great work you are doing.

**Comment by PetengDedet** [comment]
Just get same issue. 
After 3 hours of tracing the code, figured out that some of the cluster properties has and empty `latitude` or `longitude`. 😅
Filter the data before assign it to the points array. Solved.

Posted here to remind myself or others in the future for easy googling.

**Comment by nhk-nguyen** [comment]
> Just get same issue.
> After 3 hours of tracing the code, figured out that some of the cluster properties has an empty `latitude` or `longitude`. 😅
> Filter the data before assign it to the points array. Solved.
> 
> Posted here to remind myself or others in the future for easy googling.

You're right. Got the same issue and thanks to your comment!
