### ISSUE TITLE
Google Maps pass dateline infinite loop in getCluster fix

### ISSUE THREAD

**Issue by DanGDroid** [mapbox/supercluster#73]
RN 0.51
supercluster 3.0.2
bug fatal crash

hi, i'm using a RN maps with clustering using supercluster.
ios(maps) is fine,
Android(Google maps) is crashing when i go over the international dateline.

i tried to debug it to understand the problem, 
and i noticed when i pass the dataline the `zoom` becomes NaN,

log: `getClusters() => bbox: [31.949437949806452,28.57097009999041,39.08726217225194,38.12259985097466]  /// zoom: 6
index.js:76 getClusters() => bbox: [27.481803596019745,21.95397985485612,44.253987818956375,44.388517099821314]  /// zoom: 5
index.js:76 getClusters() => bbox: [27.481803596019745,21.95397985485612,44.253987818956375,44.388517099821314]  /// zoom: 5
index.js:76 getClusters() => bbox: [21.66165076196194,15.766136279534585,48.27204890549183,51.094824684911025]  /// zoom: 4
index.js:76 getClusters() => bbox: [21.66165076196194,15.766136279534585,48.27204890549183,51.094824684911025]  /// zoom: 4
index.js:76 getClusters() => bbox: [-1.530294455587864,17.282984755008922,25.080103687942028,52.08827465896199]  /// zoom: 4
index.js:76 getClusters() => bbox: [-1.530294455587864,17.282984755008922,25.080103687942028,52.08827465896199]  /// zoom: 4
index.js:76 getClusters() => bbox: [-20.88091470301151,25.147920463899432,5.729483440518378,57.029943833266906]  /// zoom: 4
index.js:76 getClusters() => bbox: [-20.88091470301151,25.147920463899432,5.729483440518378,57.029943833266906]  /// zoom: 4
index.js:76 getClusters() => bbox: [-46.071707122027874,26.01141458859852,-19.461308978497982,57.55263758644087]  /// zoom: 4
index.js:76 getClusters() => bbox: [-46.071707122027874,26.01141458859852,-19.461308978497982,57.55263758644087]  /// zoom: 4
index.js:76 getClusters() => bbox: [-52.99869161099196,26.159960960245726,-26.38829346746207,57.64218567906998]  /// zoom: 4
index.js:76 getClusters() => bbox: [-52.99869161099196,26.159960960245726,-26.38829346746207,57.64218567906998]  /// zoom: 4
index.js:76 getClusters() => bbox: [-58.12739945948123,26.166534358525205,-31.517001315951354,57.64614582103335]  /// zoom: 4
index.js:76 getClusters() => bbox: [-58.12739945948123,26.166534358525205,-31.517001315951354,57.64614582103335]  /// zoom: 4
index.js:76 getClusters() => bbox: [-64.18189521878958,26.286706263129133,-37.57149707525968,57.71850616557583]  /// zoom: 4
index.js:76 getClusters() => bbox: [-64.18189521878958,26.286706263129133,-37.57149707525968,57.71850616557583]  /// zoom: 4
index.js:76 getClusters() => bbox: [-70.77576477080584,25.844155644914174,-44.165366627275944,57.451679472303844]  /// zoom: 4
index.js:76 getClusters() => bbox: [-70.77576477080584,25.844155644914174,-44.165366627275944,57.451679472303844]  /// zoom: 4
index.js:76 getClusters() => bbox: [-78.09848707169294,26.726982821742375,-51.48808892816306,57.98301453672301]  /// zoom: 4
index.js:76 getClusters() => bbox: [-78.09848707169294,26.726982821742375,-51.48808892816306,57.98301453672301]  /// zoom: 4
index.js:76 getClusters() => bbox: [-84.74580433219671,28.24800679702512,-58.13540618866682,58.88967162971917]  /// zoom: 4
index.js:76 getClusters() => bbox: [-84.74580433219671,28.24800679702512,-58.13540618866682,58.88967162971917]  /// zoom: 4
index.js:76 getClusters() => bbox: [-95.2046673372388,29.182115200051577,-68.59426919370888,59.44110737005841]  /// zoom: 4
index.js:76 getClusters() => bbox: [-95.2046673372388,29.182115200051577,-68.59426919370888,59.44110737005841]  /// zoom: 4
index.js:76 getClusters() => bbox: [-103.39012317359447,29.246262355168298,-76.77972503006458,59.47882848427405]  /// zoom: 4
index.js:76 getClusters() => bbox: [-103.39012317359447,29.246262355168298,-76.77972503006458,59.47882848427405]  /// zoom: 4
index.js:76 getClusters() => bbox: [-114.30097728967668,29.511485532756517,-87.69057914614676,59.63459163538469]  /// zoom: 4
index.js:76 getClusters() => bbox: [-114.30097728967668,29.511485532756517,-87.69057914614676,59.63459163538469]  /// zoom: 4
index.js:76 getClusters() => bbox: [-127.56165236234666,30.021064648696914,-100.95125421881677,59.93297014263741]  /// zoom: 4
index.js:76 getClusters() => bbox: [-127.56165236234666,30.021064648696914,-100.95125421881677,59.93297014263741]  /// zoom: 4
index.js:76 getClusters() => bbox: [-142.22727689892054,30.329179932589817,-115.61687875539064,60.112818776556786]  /// zoom: 4
index.js:76 getClusters() => bbox: [-142.22727689892054,30.329179932589817,-115.61687875539064,60.112818776556786]  /// zoom: 4
index.js:76 getClusters() => bbox: [-153.265469558537,30.992003531529186,-126.65507141500711,60.49828595403742]  /// zoom: 4
index.js:76 getClusters() => bbox: [-153.265469558537,30.992003531529186,-126.65507141500711,60.49828595403742]  /// zoom: 4
index.js:76 getClusters() => bbox: [-161.56646389514208,31.717398832011405,-134.9560657516122,60.91793846852011]  /// zoom: 4
index.js:76 getClusters() => bbox: [-161.56646389514208,31.717398832011405,-134.9560657516122,60.91793846852011]  /// zoom: 4
index.js:76 getClusters() => bbox: [-169.04986124485734,32.34824376087369,-142.4394631013274,61.28104908147025]  /// zoom: 4
index.js:76 getClusters() => bbox: [-169.04986124485734,32.34824376087369,-142.4394631013274,61.28104908147025]  /// zoom: 4
index.js:76 getClusters() => bbox: [-176.35269194841385,33.280282511446096,-149.74229380488396,61.814442645245144]  /// zoom: 4
index.js:76 getClusters() => bbox: [-176.35269194841385,33.280282511446096,-149.74229380488396,61.814442645245144]  /// zoom: 4
index.js:76 getClusters() => bbox: [-182.32034280896187,34.29870892627775,-155.70994466543198,62.393155549579554]  /// zoom: 4
index.js:76 getClusters() => bbox: [-182.32034280896187,34.29870892627775,-155.70994466543198,62.393155549579554]  /// zoom: 4
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,-168.0024093389511,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN
index.js:76 getClusters() => bbox: [525.387192517519,36.78078522288718,180,63.78617953197706]  /// zoom: NaN`

that results in an endless loop of getCluster -> crash

**Comment by mourner** [comment]
Can you set up the most minimal JSFiddle/JSBin test case to reproduce the issue? That would allow us to diagnoze the issue.

**Comment by DanGDroid** [comment]
i am using supercluster with "react-native-maps-super-cluster" in mobile app.
this issue reproduces each time i pass the dateline.

**Comment by mourner** [comment]
Please provide a minimal, isolated reproducible test case (not just a description), specifically for `supercluster`. I'm afraid I won't be able to resolve the issue otherwise since we currently don't have bandwidth to diagnose third-party code like `react-native-maps-super-cluster`.

**Comment by Afsarunnisa** [comment]
We are using https://github.com/venits/react-native-map-clustering, for clustering, which internally uses supercluster, when we reach the international dateline the app is getting crashed at superCluster.getclusters method .  

here are few values when the crash is happening 

bbox (4) [129.42639028653502, -103.72001759011788, -445.93084366992116, 114.51823616744083]
bbox (4) [112.20783652737737, -84.57866659372925, -463.1493974290788, 120.16915985775583]
bbox (4) [129.88627715036273, -82.33268015457608, -445.47095680609345, 120.39093071032067]



bbox (4) [458.2200434245169, -84.2390396413517, -117.13719053193927, 120.20658595083174]
bbox (4) [456.71305837109685, -80.3541968945042, -118.64417558535933, 120.53914819019688]
bbox (4) [453.10532899573445, -75.85742277565899, -122.25190496072173, 120.73276055930677]

**Comment by mourner** [comment]
You can fix this by normalizing longitude values when forming a `bbox` value for the query. It should be in the -180..180 range.

**Comment by DanGDroid** [comment]
see similar issue: https://github.com/novalabio/react-native-maps-super-cluster/issues/20
