### ISSUE TITLE
Any plan on implementing radius in kilometers instead of pixel ? (dobbyscan)

### ISSUE THREAD

**Issue by Captain-Oski** [mapbox/supercluster#78]
Hello everyone,

Title says it all,

It would be really efficient to let us change the radius unit from pixel to map units. (m, km, miles etc...)

I looked into dobbyscan but implementing this into supercluster would be great.

Thank you in advance

**Comment by mourner** [comment]
No, since this would defeat the purpose of Supercluster — to create a hierarchical representation of point data that adjusts to zoom level (for both visual and performance reasons). Something like Dobbyscan would suit better to this task.
