### ISSUE TITLE
Add a getBounds() / getBBox() method 

### ISSUE THREAD

**Issue by hyperknot** [mapbox/supercluster#8]
A common use case in Leaflet is to set the initial map view using the fitBounds() method on a dataset. 

At the moment, supercluster doesn't have any way of returning its bounds, although I guess rbush / kdbush would probably be able to return it in O(1) time.

As a workaround my only idea is to use a temporary GeoJSON group (not added to L.Map) and use it to calculate the fitBounds() of the dataset. This workaround is quite bad both for performance and memory reasons.

About the format of getBounds / getBBox: I think a simple [W, S, E, N] array would be a rational choice without adding any framework dependencies.

**Comment by mourner** [comment]
I don't think it's possible to get it in O(1) anymore after switching to KDBush. However, you could easily loop through all the points once to get a bbox in the application code — it's just a few lines of code, no need to put them into temporary GeoJSON groups etc.

**Comment by hyperknot** [comment]
I agree it would be straightforward to make an O(N) implementation in client side.

On the other hand, if you ever extend KDBush to return this via O(1) it would be a great addition to supercluster.

**Comment by mourner** [comment]
There's no easy way to add this to KDBush, and it would perform the same as a client-side loop, so I think we should leave this outside of the library.
