### ISSUE TITLE
click on cluster and show callout with average values of children markers

### ISSUE THREAD

**Issue by impossible-creations** [mapbox/supercluster#83]
hello, 

when clicking each marker, a callout with 'title' and 'description' works fine. I have also set a 'value' for each marker (e.g. 200, 300, 400...).

when zooming out, the markers group into clusters, and when clicking on it, I wish to give a callout displaying the average of the 'value' (e.g. (200 + 300 + 400) / 3). I know this can be achieved by setting 'title' and 'description' again on the cluster.

After reading the doc, I tried getChildren(clusterId). This function will work when cluster exists, and will give error when no cluster exists (e.g. when zoom very big).

I also read through the scripts, but I am not sure where I can pass makers info into a particular cluster when it forms.

Could you give me some suggestion? Thanks a lot.

**Comment by mourner** [comment]
What you're looking for is map/reduce options described here https://github.com/mapbox/supercluster#property-mapreduce-options
