### ISSUE TITLE
getLeaves Doubt

### ISSUE THREAD

**Issue by longqiuqiu** [mapbox/supercluster#84]
At a certain level, some can trigger, others can not trigger.
this is the right ![image](https://user-images.githubusercontent.com/12045406/40401188-dccbd60c-5e77-11e8-920f-c25f7ae43750.png),

but this 
![image](https://user-images.githubusercontent.com/12045406/40401225-0201da34-5e78-11e8-83e0-9d716fc32457.png),
They are at the same scale at the zoom level.

I'm not sure if it's the problem. [#72](https://github.com/mapbox/supercluster/issues/72)

Here is  [demo](https://jsfiddle.net/aznkw784/49/)

Thanks in advance.

**Comment by mourner** [comment]
Your demo is quite involved, making it difficult to diagnose the issue. Can you make a minimal test case?

**Comment by mourner** [comment]
@longqiuqiu did you resolve the issue yourself?

**Comment by longqiuqiu** [comment]
No, I haven't solved it yet. Now, the focus of my work is that I have no time to solve it.I think when I have time, I will rearrange the problems and find solutions.

**Comment by JFernandoGomez** [comment]
same case

**Comment by mourner** [comment]
@JFernandoGomez can you set up a minimal test case? Struggling to reproduce any problems with pure Supercluster — everything works for me.
