### ISSUE TITLE
getClusters() returns an empty array on v3.0.3

### ISSUE THREAD

**Issue by GadyTal** [mapbox/supercluster#86]
Hi @mourner,

I'm working with mapboxGL js v0.45 and supercluster v3.0.2.

About 7 days ago, the clusters stopped work and just disappeared, w/o any issue or console errors.
After a lot of research, I've found that `.getClusters()` function returns an empty array. 

I get that there is an error that started with v3.0.3 release.
The calculation of the bbox, at the beginning of the `getClusters()` returns false values.

`getClusters` function was called with: `bbox (world-bounds) - [-180.0000, -90.0000, 180.0000, 90.0000]` but changed the bbox values to: `[90, -180, -90, -180]`.

The relevant lines:
```
        var minLng = ((bbox[0] + 180) % 360 + 360) % 360 - 180;
        var minLat = Math.max(-90, Math.min(90, bbox[1]));
        var maxLng = ((bbox[2] + 180) % 360 + 360) % 360 - 180;
        var maxLat = Math.max(-90, Math.min(90, bbox[3]));
```

I believe that it's an issue with the crash fix on v3.0.3, not sure how to fix it.
Thanks,
Gady

**Comment by mourner** [comment]
Confirmed, will roll out a fix today. Thanks for the report!

**Comment by mourner** [comment]
Hopefully fixed in v4.0.1. Please try it out and let me know how if it works OK!

**Comment by GadyTal** [comment]
Happy to help, thx!

**Comment by hrkfdn** [comment]
I still have this problem in 4.0.1, I'm afraid.

**Comment by mourner** [comment]
@hrkfdn can you provide a minimal test case that reproduces this? The original reported above works.
