### ISSUE TITLE
Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by 3zzy** [mapbox/supercluster#87]
```
map.on('moveend', updateClusters);

var updateClusters = function (e) {  
    var bounds = map.getBounds(),
        zoom = map.getZoom();
    
    clustersGeojson = clusterIndex.getClusters([
        bounds.getWest(),
        bounds.getSouth(),
        bounds.getEast(),
        bounds.getNorth()
    ], zoom);

    if (clusters.length > 0) {
        $.each(clusters, function (i, cluster) {
            if (cluster !== undefined) cluster.remove();
        });
    }

    displayFeatures(clustersGeojson);
};
```

Although this works as expected but quite frequently I get an error when zooming in/out too quickly:

```
Uncaught TypeError: Cannot read property 'range' of undefined
    at o.getClusters (mapbox-supercluster.js?_v=2.8.2.0:1)
```

What am I missing?

Thanks!

**Comment by mourner** [comment]
I'm not sure — could you try reducing this to a minimal live test case?

**Comment by 3zzy** [comment]
@mourner  Here you go: https://jsfiddle.net/iaezzy/xpvt214o/242578/

So If you try zooming with the +/ - controls slowly everything works, but if you zoom in/out too fast (or using the scroll wheel) it throws that error.

**Comment by mourner** [comment]
Supercluster expects round zoom values, so if you do something like `Math.floor(zoom)` when passing it to `getClusters`, it will work without errors.
