### ISSUE TITLE
Add feature `id` value to supercluster output

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/supercluster#88]
# Problem

GL JS v0.46.0 launched the setFeatureState() API, which allows a feature to be updated at run-time using the tile feature index.  Supercluster does not add a feature `id` value to each geojson object.

# Current supercluster output in GL JS

![](https://cl.ly/2w3G3o383f0R/download/Image%202018-06-25%20at%207.03.41%20AM.png)

# Proposed Solution

* Use the `cluster_id` as a vector tile feature `id` for sources created with Supercluster, allowing clusters to be used with setFeatureState for hover and highlight interactions with cluster layers in GL JS.

cc/ @mourner

**Comment by mourner** [comment]
Should we remove the `cluster_id` feature property in favor of `id` (a breaking change), or just duplicate it for compatibility?

**Comment by ryanbaumann** [comment]
I'm in favor of duplication.  Both to remain backward compatible with older supercluster versions, and because the feature `id` property is a less descriptive name than the current `cluster_id` property name.

**Comment by asheemmamoowala** [comment]
Fixed in #94.
