### ISSUE TITLE
How to use supercluster

### ISSUE THREAD

**Issue by HADDADENICAR** [mapbox/supercluster#89]
I'am new to mapbox. I need to use the supercluster project of mapbox in order to plot 6 millions of gps in a map. i tried to use the demo in localhost but i only get an empty map !?
this is my code in index.html :

      <!DOCTYPE html>
       <html>
            <head>
             <meta charset="utf-8">
             <title>Supercluster Leaflet demo</title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.js"></script>

        <link rel="stylesheet" href="cluster.css" />

        <style>
            html, body, #map {
            height: 100%;
            margin: 0;
            }
        </style>
        </head>
        <body>
          <div id="map"></div>
         <script src="index.js"></script>
         <script src="https://unpkg.com/supercluster@3.0.2/dist/supercluster.min.js">

       var index = supercluster({
         radius: 40,
         maxZoom: 16
       });
       index.load(GeoObs.features);
       index.getClusters([-180, -85, 180, 85], 2);
     </script>
         </body>
    </html>

**Comment by mourner** [comment]
The easiest way to use Supercluster is to use it as a part of Mapbox GL JS, e.g. like in this example: https://www.mapbox.com/mapbox-gl-js/example/cluster/

I'm closing the issue because it's place to report bugs, not ask for general help.

**Comment by HADDADENICAR** [comment]
I Solved [my issue on StackOverflow](https://stackoverflow.com/questions/51033188/how-to-use-supercluster/51091977#51091977)
