### ISSUE TITLE
How can supercluster be integrated with Folium?

### ISSUE THREAD

**Issue by HADDADENICAR** [mapbox/supercluster#90]
Folium is the python implementation of leaflet.

It is possible in folium as well in leaflet to use markercluster when the number of gps grows.
But markercluster have a limit of 50k gps , recently i found that the owner of leaflet have created another clustring algorithme for huge spatial data called supercluster that can handle 6 millions of gps.

my question is:
Is it possible to use the leaflet supercluster on folium maps ?
if yes how to use it on folium ?

**Comment by mourner** [comment]
I don't know to be honest. You should ask the authors of Folium.
