### ISSUE TITLE
client-side clustring or server-side clustring

### ISSUE THREAD

**Issue by HADDADENICAR** [mapbox/supercluster#91]
I am doing my final year project, your supercluster is very fast, so i m asking is that a server-side clustring or a client-side clustring ?
thanks

**Comment by andresteves** [comment]
You can implement it either way.

**Comment by HADDADENICAR** [comment]
ok thanks for your response.
what about this project  is it server-side ?

**Comment by andresteves** [comment]
Server-side.

**Comment by mourner** [comment]
The library was designed to be used client-side (as a part of Mapbox GL JS), but can be used as server-side (with Node.js) too.
