### ISSUE TITLE
what is the limit of supercluster

### ISSUE THREAD

**Issue by HADDADENICAR** [mapbox/supercluster#95]
the browser is blocking the reading of the geojson file for memory reasons
this is what i get:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/Users/Ahmed/Desktop/supercluster-master/supercluster-master/test/fixtures/taxi2.geojson. (Reason: CORS request not http).

    Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (165286 px). Occurrences of will-change over the budget will be ignored.

**Comment by mourner** [comment]
These are two independent, unrelated messages. The first one is about a CORS security restriction (trying to do an XMLHttpRequest under a file:// page) — to fix it, you need to serve your page with a static server.

The second one is about CSS property `will-change`, and is also not related to Supercluster in any way.

**Comment by HADDADENICAR** [comment]
>to fix it, you need to serve your page with a static server.
how to do that ? you mean i need to run a node.js server ?

**Comment by mourner** [comment]
This is not a place to ask programming questions. Please use StackOverflow or a similar service, or just Google.
